// Code generated by protoc-gen-go. DO NOT EDIT.
// source: status/statuspb/status.proto

/*
Package statuspb is a generated protocol buffer package.

It is generated from these files:
	status/statuspb/status.proto

It has these top-level messages:
	DiskInfo
	NodeInfo
	BackupInfo
	FullBackupInfo
	IncBackupInfo
*/
package statuspb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StoredType int32

const (
	StoredType_LOCAL StoredType = 0
)

var StoredType_name = map[int32]string{
	0: "LOCAL",
}
var StoredType_value = map[string]int32{
	"LOCAL": 0,
}

func (x StoredType) String() string {
	return proto.EnumName(StoredType_name, int32(x))
}
func (StoredType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DiskInfo struct {
	Total uint64 `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
	Avail uint64 `protobuf:"varint,2,opt,name=avail" json:"avail,omitempty"`
}

func (m *DiskInfo) Reset()                    { *m = DiskInfo{} }
func (m *DiskInfo) String() string            { return proto.CompactTextString(m) }
func (*DiskInfo) ProtoMessage()               {}
func (*DiskInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DiskInfo) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *DiskInfo) GetAvail() uint64 {
	if m != nil {
		return m.Avail
	}
	return 0
}

type NodeInfo struct {
	DiskInfo *DiskInfo `protobuf:"bytes,1,opt,name=diskInfo" json:"diskInfo,omitempty"`
	Addr     string    `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
}

func (m *NodeInfo) Reset()                    { *m = NodeInfo{} }
func (m *NodeInfo) String() string            { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()               {}
func (*NodeInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NodeInfo) GetDiskInfo() *DiskInfo {
	if m != nil {
		return m.DiskInfo
	}
	return nil
}

func (m *NodeInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type BackupInfo struct {
	Db         string           `protobuf:"bytes,1,opt,name=db" json:"db,omitempty"`
	FullBackup *FullBackupInfo  `protobuf:"bytes,2,opt,name=full_backup,json=fullBackup" json:"full_backup,omitempty"`
	IncBackups []*IncBackupInfo `protobuf:"bytes,3,rep,name=inc_backups,json=incBackups" json:"inc_backups,omitempty"`
}

func (m *BackupInfo) Reset()                    { *m = BackupInfo{} }
func (m *BackupInfo) String() string            { return proto.CompactTextString(m) }
func (*BackupInfo) ProtoMessage()               {}
func (*BackupInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BackupInfo) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *BackupInfo) GetFullBackup() *FullBackupInfo {
	if m != nil {
		return m.FullBackup
	}
	return nil
}

func (m *BackupInfo) GetIncBackups() []*IncBackupInfo {
	if m != nil {
		return m.IncBackups
	}
	return nil
}

type FullBackupInfo struct {
	StoredTime int64      `protobuf:"varint,1,opt,name=stored_time,json=storedTime" json:"stored_time,omitempty"`
	NodeName   string     `protobuf:"bytes,2,opt,name=node_name,json=nodeName" json:"node_name,omitempty"`
	Host       string     `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
	StoredType StoredType `protobuf:"varint,4,opt,name=stored_type,json=storedType,enum=statuspb.StoredType" json:"stored_type,omitempty"`
}

func (m *FullBackupInfo) Reset()                    { *m = FullBackupInfo{} }
func (m *FullBackupInfo) String() string            { return proto.CompactTextString(m) }
func (*FullBackupInfo) ProtoMessage()               {}
func (*FullBackupInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FullBackupInfo) GetStoredTime() int64 {
	if m != nil {
		return m.StoredTime
	}
	return 0
}

func (m *FullBackupInfo) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *FullBackupInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *FullBackupInfo) GetStoredType() StoredType {
	if m != nil {
		return m.StoredType
	}
	return StoredType_LOCAL
}

type IncBackupInfo struct {
	StoredTime int64      `protobuf:"varint,1,opt,name=stored_time,json=storedTime" json:"stored_time,omitempty"`
	NodeName   string     `protobuf:"bytes,2,opt,name=node_name,json=nodeName" json:"node_name,omitempty"`
	Host       string     `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
	StoredType StoredType `protobuf:"varint,4,opt,name=stored_type,json=storedType,enum=statuspb.StoredType" json:"stored_type,omitempty"`
}

func (m *IncBackupInfo) Reset()                    { *m = IncBackupInfo{} }
func (m *IncBackupInfo) String() string            { return proto.CompactTextString(m) }
func (*IncBackupInfo) ProtoMessage()               {}
func (*IncBackupInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *IncBackupInfo) GetStoredTime() int64 {
	if m != nil {
		return m.StoredTime
	}
	return 0
}

func (m *IncBackupInfo) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *IncBackupInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *IncBackupInfo) GetStoredType() StoredType {
	if m != nil {
		return m.StoredType
	}
	return StoredType_LOCAL
}

func init() {
	proto.RegisterType((*DiskInfo)(nil), "statuspb.DiskInfo")
	proto.RegisterType((*NodeInfo)(nil), "statuspb.NodeInfo")
	proto.RegisterType((*BackupInfo)(nil), "statuspb.BackupInfo")
	proto.RegisterType((*FullBackupInfo)(nil), "statuspb.FullBackupInfo")
	proto.RegisterType((*IncBackupInfo)(nil), "statuspb.IncBackupInfo")
	proto.RegisterEnum("statuspb.StoredType", StoredType_name, StoredType_value)
}

func init() { proto.RegisterFile("status/statuspb/status.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x92, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0xed, 0xba, 0x49, 0x7b, 0x8a, 0x43, 0xc2, 0x60, 0x05, 0x05, 0x47, 0xaf, 0x86, 0x17,
	0x15, 0x2a, 0x8a, 0x5e, 0xfa, 0x07, 0x61, 0x30, 0x26, 0x54, 0xef, 0x47, 0xba, 0x64, 0x18, 0x96,
	0x36, 0x61, 0x49, 0x85, 0x3d, 0x86, 0x77, 0xfa, 0xb6, 0xd2, 0xa4, 0x5d, 0xdc, 0x1b, 0x78, 0xd5,
	0x73, 0xbe, 0x9e, 0xef, 0x77, 0xbe, 0x03, 0x81, 0x73, 0xa5, 0xb1, 0xae, 0xd5, 0x95, 0xfd, 0xc8,
	0xa2, 0x2d, 0x52, 0xb9, 0x15, 0x5a, 0xa0, 0xa0, 0x93, 0x93, 0x5b, 0x08, 0x9e, 0x99, 0xda, 0xcc,
	0xaa, 0xb5, 0x40, 0x23, 0x18, 0x68, 0xa1, 0x31, 0x8f, 0xbd, 0x89, 0x37, 0xed, 0xe7, 0xb6, 0x69,
	0x54, 0xfc, 0x89, 0x19, 0x8f, 0x7b, 0x56, 0x35, 0x4d, 0xb2, 0x80, 0x60, 0x21, 0x08, 0x35, 0xbe,
	0x14, 0x02, 0xd2, 0x32, 0x8c, 0x35, 0xca, 0x50, 0xda, 0x2d, 0x48, 0x3b, 0x7a, 0xbe, 0x9f, 0x41,
	0x08, 0xfa, 0x98, 0x90, 0xad, 0x01, 0x86, 0xb9, 0xa9, 0x93, 0x2f, 0x0f, 0xe0, 0x11, 0xaf, 0x36,
	0xb5, 0x34, 0x23, 0x43, 0xe8, 0x91, 0xc2, 0xc0, 0xc2, 0xbc, 0x47, 0x0a, 0x74, 0x0f, 0xd1, 0xba,
	0xe6, 0x7c, 0x59, 0x98, 0x11, 0xe3, 0x8c, 0xb2, 0xd8, 0x6d, 0x79, 0xa9, 0x39, 0x77, 0xf6, 0x1c,
	0xd6, 0xfb, 0x1e, 0xdd, 0x41, 0xc4, 0xaa, 0x55, 0xeb, 0x54, 0xb1, 0x3f, 0xf1, 0xa7, 0x51, 0x36,
	0x76, 0xd6, 0x59, 0xb5, 0xfa, 0xeb, 0x64, 0x5d, 0xab, 0x92, 0x1f, 0x0f, 0x86, 0x87, 0x60, 0x74,
	0x01, 0x91, 0xd2, 0x62, 0x4b, 0xc9, 0x52, 0xb3, 0x92, 0x9a, 0x80, 0x7e, 0x0e, 0x56, 0x7a, 0x67,
	0x25, 0x45, 0x67, 0x10, 0x56, 0x82, 0xd0, 0x65, 0x85, 0x4b, 0xda, 0x1e, 0x18, 0x34, 0xc2, 0x02,
	0x97, 0xb4, 0x39, 0xfc, 0x43, 0x28, 0x1d, 0xfb, 0xf6, 0xf0, 0xa6, 0x46, 0x37, 0x8e, 0xb8, 0x93,
	0x34, 0xee, 0x4f, 0xbc, 0xe9, 0x30, 0x1b, 0xb9, 0x78, 0x6f, 0x96, 0xbd, 0x93, 0x74, 0xbf, 0x67,
	0x27, 0x69, 0xf2, 0xed, 0xc1, 0xc9, 0x41, 0xf2, 0x7f, 0x13, 0xed, 0x72, 0x0c, 0xe0, 0xfe, 0xa0,
	0x10, 0x06, 0xf3, 0xd7, 0xa7, 0x87, 0xf9, 0xe9, 0x51, 0x71, 0x6c, 0x1e, 0xdf, 0xf5, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xc9, 0x0c, 0x4f, 0xd6, 0x9c, 0x02, 0x00, 0x00,
}
