// Code generated by protoc-gen-go. DO NOT EDIT.
// source: status/statuspb/status.proto

/*
Package statuspb is a generated protocol buffer package.

It is generated from these files:
	status/statuspb/status.proto

It has these top-level messages:
	DiskInfo
	NodeInfo
	NodeInfoMap
	BackupInfo
	FullBackupInfo
	IncBackupInfo
	AllBackups
*/
package statuspb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StoredType int32

const (
	StoredType_LOCAL StoredType = 0
)

var StoredType_name = map[int32]string{
	0: "LOCAL",
}
var StoredType_value = map[string]int32{
	"LOCAL": 0,
}

func (x StoredType) String() string {
	return proto.EnumName(StoredType_name, int32(x))
}
func (StoredType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DiskInfo struct {
	Total uint64 `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
	Avail uint64 `protobuf:"varint,2,opt,name=avail" json:"avail,omitempty"`
}

func (m *DiskInfo) Reset()                    { *m = DiskInfo{} }
func (m *DiskInfo) String() string            { return proto.CompactTextString(m) }
func (*DiskInfo) ProtoMessage()               {}
func (*DiskInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DiskInfo) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *DiskInfo) GetAvail() uint64 {
	if m != nil {
		return m.Avail
	}
	return 0
}

type NodeInfo struct {
	DiskInfo *DiskInfo `protobuf:"bytes,1,opt,name=diskInfo" json:"diskInfo,omitempty"`
	Addr     string    `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
	StoreDir string    `protobuf:"bytes,3,opt,name=store_dir,json=storeDir" json:"store_dir,omitempty"`
}

func (m *NodeInfo) Reset()                    { *m = NodeInfo{} }
func (m *NodeInfo) String() string            { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()               {}
func (*NodeInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NodeInfo) GetDiskInfo() *DiskInfo {
	if m != nil {
		return m.DiskInfo
	}
	return nil
}

func (m *NodeInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *NodeInfo) GetStoreDir() string {
	if m != nil {
		return m.StoreDir
	}
	return ""
}

type NodeInfoMap struct {
	Nodes map[string]*NodeInfo `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *NodeInfoMap) Reset()                    { *m = NodeInfoMap{} }
func (m *NodeInfoMap) String() string            { return proto.CompactTextString(m) }
func (*NodeInfoMap) ProtoMessage()               {}
func (*NodeInfoMap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NodeInfoMap) GetNodes() map[string]*NodeInfo {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type BackupInfo struct {
	FullBackup *FullBackupInfo  `protobuf:"bytes,1,opt,name=full_backup,json=fullBackup" json:"full_backup,omitempty"`
	IncBackups []*IncBackupInfo `protobuf:"bytes,2,rep,name=inc_backups,json=incBackups" json:"inc_backups,omitempty"`
}

func (m *BackupInfo) Reset()                    { *m = BackupInfo{} }
func (m *BackupInfo) String() string            { return proto.CompactTextString(m) }
func (*BackupInfo) ProtoMessage()               {}
func (*BackupInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BackupInfo) GetFullBackup() *FullBackupInfo {
	if m != nil {
		return m.FullBackup
	}
	return nil
}

func (m *BackupInfo) GetIncBackups() []*IncBackupInfo {
	if m != nil {
		return m.IncBackups
	}
	return nil
}

type FullBackupInfo struct {
	StoredTime *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=stored_time,json=storedTime" json:"stored_time,omitempty"`
	NodeName   string                     `protobuf:"bytes,2,opt,name=node_name,json=nodeName" json:"node_name,omitempty"`
	Host       string                     `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
	StoredType StoredType                 `protobuf:"varint,4,opt,name=stored_type,json=storedType,enum=statuspb.StoredType" json:"stored_type,omitempty"`
	EndTime    *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	FileSize   uint64                     `protobuf:"varint,6,opt,name=file_size,json=fileSize" json:"file_size,omitempty"`
}

func (m *FullBackupInfo) Reset()                    { *m = FullBackupInfo{} }
func (m *FullBackupInfo) String() string            { return proto.CompactTextString(m) }
func (*FullBackupInfo) ProtoMessage()               {}
func (*FullBackupInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FullBackupInfo) GetStoredTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.StoredTime
	}
	return nil
}

func (m *FullBackupInfo) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *FullBackupInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *FullBackupInfo) GetStoredType() StoredType {
	if m != nil {
		return m.StoredType
	}
	return StoredType_LOCAL
}

func (m *FullBackupInfo) GetEndTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *FullBackupInfo) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type IncBackupInfo struct {
	StoredTime *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=stored_time,json=storedTime" json:"stored_time,omitempty"`
	NodeName   string                     `protobuf:"bytes,2,opt,name=node_name,json=nodeName" json:"node_name,omitempty"`
	Host       string                     `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
	StoredType StoredType                 `protobuf:"varint,4,opt,name=stored_type,json=storedType,enum=statuspb.StoredType" json:"stored_type,omitempty"`
	EndTime    *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	FileSize   uint64                     `protobuf:"varint,6,opt,name=file_size,json=fileSize" json:"file_size,omitempty"`
}

func (m *IncBackupInfo) Reset()                    { *m = IncBackupInfo{} }
func (m *IncBackupInfo) String() string            { return proto.CompactTextString(m) }
func (*IncBackupInfo) ProtoMessage()               {}
func (*IncBackupInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *IncBackupInfo) GetStoredTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.StoredTime
	}
	return nil
}

func (m *IncBackupInfo) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *IncBackupInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *IncBackupInfo) GetStoredType() StoredType {
	if m != nil {
		return m.StoredType
	}
	return StoredType_LOCAL
}

func (m *IncBackupInfo) GetEndTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *IncBackupInfo) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type AllBackups struct {
	DbToBackups map[string]*BackupInfo `protobuf:"bytes,1,rep,name=db_to_backups,json=dbToBackups" json:"db_to_backups,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AllBackups) Reset()                    { *m = AllBackups{} }
func (m *AllBackups) String() string            { return proto.CompactTextString(m) }
func (*AllBackups) ProtoMessage()               {}
func (*AllBackups) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AllBackups) GetDbToBackups() map[string]*BackupInfo {
	if m != nil {
		return m.DbToBackups
	}
	return nil
}

func init() {
	proto.RegisterType((*DiskInfo)(nil), "statuspb.DiskInfo")
	proto.RegisterType((*NodeInfo)(nil), "statuspb.NodeInfo")
	proto.RegisterType((*NodeInfoMap)(nil), "statuspb.NodeInfoMap")
	proto.RegisterType((*BackupInfo)(nil), "statuspb.BackupInfo")
	proto.RegisterType((*FullBackupInfo)(nil), "statuspb.FullBackupInfo")
	proto.RegisterType((*IncBackupInfo)(nil), "statuspb.IncBackupInfo")
	proto.RegisterType((*AllBackups)(nil), "statuspb.AllBackups")
	proto.RegisterEnum("statuspb.StoredType", StoredType_name, StoredType_value)
}

func init() { proto.RegisterFile("status/statuspb/status.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x53, 0x51, 0x6b, 0xdb, 0x3c,
	0x14, 0xfd, 0xec, 0xc4, 0xfd, 0x9c, 0x6b, 0x5a, 0x82, 0x28, 0xd4, 0x64, 0x83, 0x05, 0xc3, 0x20,
	0xf4, 0xc1, 0x81, 0x8c, 0x96, 0x6e, 0x7b, 0xea, 0x96, 0x0d, 0x02, 0x59, 0x07, 0x6e, 0xde, 0x8d,
	0x1c, 0xcb, 0x9d, 0x88, 0x63, 0x19, 0x4b, 0x2e, 0xb8, 0x6f, 0x7b, 0xdb, 0x9e, 0xf7, 0x3b, 0xf6,
	0x1f, 0x87, 0x25, 0xcb, 0x4a, 0xc6, 0x60, 0x3f, 0x60, 0x4f, 0xbe, 0x3a, 0x3e, 0xf7, 0xea, 0xe8,
	0xdc, 0x7b, 0xe1, 0x39, 0x17, 0x58, 0xd4, 0x7c, 0xae, 0x3e, 0x65, 0xd2, 0x05, 0x61, 0x59, 0x31,
	0xc1, 0x90, 0xab, 0xe1, 0xc9, 0x8b, 0x07, 0xc6, 0x1e, 0x72, 0x32, 0x97, 0x78, 0x52, 0x67, 0x73,
	0x41, 0xf7, 0x84, 0x0b, 0xbc, 0x2f, 0x15, 0x35, 0xb8, 0x06, 0x77, 0x49, 0xf9, 0x6e, 0x55, 0x64,
	0x0c, 0x9d, 0x83, 0x23, 0x98, 0xc0, 0xb9, 0x6f, 0x4d, 0xad, 0xd9, 0x30, 0x52, 0x87, 0x16, 0xc5,
	0x8f, 0x98, 0xe6, 0xbe, 0xad, 0x50, 0x79, 0x08, 0x76, 0xe0, 0xde, 0xb1, 0x94, 0xc8, 0xbc, 0x10,
	0xdc, 0xb4, 0xab, 0x21, 0x53, 0xbd, 0x05, 0x0a, 0xb5, 0x82, 0x50, 0x57, 0x8f, 0x7a, 0x0e, 0x42,
	0x30, 0xc4, 0x69, 0x5a, 0xc9, 0x82, 0xa3, 0x48, 0xc6, 0xe8, 0x19, 0x8c, 0xb8, 0x60, 0x15, 0x89,
	0x53, 0x5a, 0xf9, 0x03, 0xf9, 0xc3, 0x95, 0xc0, 0x92, 0x56, 0xc1, 0x0f, 0x0b, 0x3c, 0x7d, 0xdb,
	0x27, 0x5c, 0xa2, 0x6b, 0x70, 0x0a, 0x96, 0x12, 0xee, 0x5b, 0xd3, 0xc1, 0xcc, 0x5b, 0x4c, 0xcd,
	0x6d, 0x07, 0x2c, 0x19, 0xf3, 0x0f, 0x85, 0xa8, 0x9a, 0x48, 0xd1, 0x27, 0x6b, 0x00, 0x03, 0xa2,
	0x31, 0x0c, 0x76, 0xa4, 0x91, 0x8a, 0x47, 0x51, 0x1b, 0xa2, 0x19, 0x38, 0x8f, 0x38, 0xaf, 0x89,
	0x54, 0x76, 0xf4, 0x0a, 0x5d, 0x37, 0x52, 0x84, 0x37, 0xf6, 0x8d, 0x15, 0x7c, 0xb5, 0x00, 0xde,
	0xe1, 0xed, 0xae, 0x2e, 0xe5, 0xab, 0x5e, 0x83, 0x97, 0xd5, 0x79, 0x1e, 0x27, 0x12, 0xea, 0x8c,
	0xf0, 0x4d, 0x89, 0x8f, 0x75, 0x9e, 0x1b, 0x7a, 0x04, 0x59, 0x7f, 0x46, 0x37, 0xe0, 0xd1, 0x62,
	0xdb, 0x65, 0x72, 0xdf, 0x96, 0xaf, 0xba, 0x30, 0xa9, 0xab, 0x62, 0x7b, 0x98, 0x49, 0xf5, 0x91,
	0x07, 0xdf, 0x6d, 0x38, 0x3b, 0x2e, 0x8c, 0xde, 0x82, 0x27, 0x8d, 0x4b, 0xe3, 0xb6, 0xd7, 0x9d,
	0x8e, 0x49, 0xa8, 0x06, 0x21, 0xd4, 0x83, 0x10, 0x6e, 0xf4, 0x20, 0x44, 0xa0, 0xe8, 0x2d, 0xd0,
	0xb6, 0xa1, 0xb5, 0x2a, 0x2e, 0xf0, 0x9e, 0x74, 0xfd, 0x71, 0x5b, 0xe0, 0x0e, 0xef, 0x49, 0xdb,
	0xb7, 0x2f, 0x8c, 0x8b, 0xae, 0x3d, 0x32, 0x46, 0x57, 0xe6, 0xb6, 0xa6, 0x24, 0xfe, 0x70, 0x6a,
	0xcd, 0xce, 0x16, 0xe7, 0x46, 0xfa, 0xbd, 0xaa, 0xdd, 0x94, 0xa4, 0xbf, 0xa7, 0x29, 0x09, 0xba,
	0x02, 0x97, 0x14, 0x9d, 0x42, 0xe7, 0xaf, 0x0a, 0xff, 0x27, 0x45, 0x2f, 0x2f, 0xa3, 0x39, 0x89,
	0x39, 0x7d, 0x22, 0xfe, 0x89, 0x9c, 0x47, 0xb7, 0x05, 0xee, 0xe9, 0x13, 0x09, 0xbe, 0xd9, 0x70,
	0x7a, 0xe4, 0xd4, 0xbf, 0x6b, 0xc5, 0x4f, 0x0b, 0xe0, 0x56, 0x4f, 0x05, 0x47, 0x2b, 0x38, 0x4d,
	0x93, 0x58, 0xb0, 0x7e, 0xc2, 0xd4, 0xde, 0xbc, 0x34, 0xda, 0x0c, 0x39, 0x5c, 0x26, 0x1b, 0xd6,
	0xc5, 0x6a, 0x79, 0xbc, 0xd4, 0x20, 0x93, 0x0d, 0x8c, 0x7f, 0x27, 0xfc, 0x61, 0x91, 0x2e, 0x8f,
	0x17, 0xe9, 0xc0, 0x84, 0x83, 0x39, 0x36, 0xab, 0x74, 0x79, 0x01, 0x60, 0xdc, 0x41, 0x23, 0x70,
	0xd6, 0x9f, 0xdf, 0xdf, 0xae, 0xc7, 0xff, 0x25, 0x27, 0xd2, 0x82, 0x57, 0xbf, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x50, 0xeb, 0xcf, 0xc0, 0xf0, 0x04, 0x00, 0x00,
}
