FROM buildpack-deps:xenial-scm

MAINTAINER Takuya Kuwahara <taakuu19@gmail.com>

# Make sure apt-get is up to date and dependent packages are installed
RUN \
  apt-get update && \
  apt-get install -y software-properties-common && \
  add-apt-repository 'deb http://archive.ubuntu.com/ubuntu trusty universe' && \
  echo "mysql-server mysql-server/root_password password root" | debconf-set-selections && \
  echo "mysql-server mysql-server/root_password_again password root" | debconf-set-selections && \
  apt-get update && \
  apt-get install -y mysql-server-5.6 \
    --no-install-recommends

# Install go 1.8.3
RUN \
  wget -q https://golang.org/dl/go1.8.3.linux-amd64.tar.gz && \
  tar -C /usr/local -xzf `basename https://golang.org/dl/go1.8.3.linux-amd64.tar.gz`
ENV PATH   /go/bin:/usr/local/go/bin:$PATH
ENV GOPATH /go
ENV GOROOT /usr/local/go

# Install Xtrabackup 2.3.8
RUN \
  wget -q https://repo.percona.com/apt/percona-release_0.1-4.xenial_all.deb && \
  dpkg -i percona-release_0.1-4.xenial_all.deb && \
  apt-get update && \
  apt-get install -y percona-xtrabackup=2.3.8-1.xenial

ENV PKG github.com/taku-k/polymerase
WORKDIR /go/src/$PKG
ADD pkg /go/src/$PKG/pkg
ADD vendor /go/src/$PKG/vendor
ADD Makefile main.go /go/src/$PKG/
RUN go install

ADD integration-test/my.cnf /etc/mysql/my.cnf
ADD test.sh /
