[[constraint]]
  name = "github.com/cheggaaa/pb"
  version = "1.0.15"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  name = "github.com/elastic/gosigar"
  version = "0.4.0"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.27.2"

[[constraint]]
  branch = "master"
  name = "github.com/jhoonb/archivex"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/petermattis/goid"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "go.uber.org/ratelimit"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/fortytw2/leaktest"
