// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/admin/admin.proto

/*
Package admin is a generated protocol buffer package.

It is generated from these files:
	server/admin/admin.proto

It has these top-level messages:
	BackupsRequest
	BackupsResponse
	BackupInfoWithKey
*/
package admin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import statuspb "status/statuspb"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BackupsRequest struct {
}

func (m *BackupsRequest) Reset()                    { *m = BackupsRequest{} }
func (m *BackupsRequest) String() string            { return proto.CompactTextString(m) }
func (*BackupsRequest) ProtoMessage()               {}
func (*BackupsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type BackupsResponse struct {
	Backups []*BackupInfoWithKey `protobuf:"bytes,1,rep,name=backups" json:"backups,omitempty"`
}

func (m *BackupsResponse) Reset()                    { *m = BackupsResponse{} }
func (m *BackupsResponse) String() string            { return proto.CompactTextString(m) }
func (*BackupsResponse) ProtoMessage()               {}
func (*BackupsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BackupsResponse) GetBackups() []*BackupInfoWithKey {
	if m != nil {
		return m.Backups
	}
	return nil
}

type BackupInfoWithKey struct {
	Key  string               `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Info *statuspb.BackupInfo `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *BackupInfoWithKey) Reset()                    { *m = BackupInfoWithKey{} }
func (m *BackupInfoWithKey) String() string            { return proto.CompactTextString(m) }
func (*BackupInfoWithKey) ProtoMessage()               {}
func (*BackupInfoWithKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BackupInfoWithKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *BackupInfoWithKey) GetInfo() *statuspb.BackupInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*BackupsRequest)(nil), "admin.BackupsRequest")
	proto.RegisterType((*BackupsResponse)(nil), "admin.BackupsResponse")
	proto.RegisterType((*BackupInfoWithKey)(nil), "admin.BackupInfoWithKey")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Admin service

type AdminClient interface {
	Backups(ctx context.Context, in *BackupsRequest, opts ...grpc.CallOption) (*BackupsResponse, error)
}

type adminClient struct {
	cc *grpc.ClientConn
}

func NewAdminClient(cc *grpc.ClientConn) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) Backups(ctx context.Context, in *BackupsRequest, opts ...grpc.CallOption) (*BackupsResponse, error) {
	out := new(BackupsResponse)
	err := grpc.Invoke(ctx, "/admin.Admin/Backups", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Admin service

type AdminServer interface {
	Backups(context.Context, *BackupsRequest) (*BackupsResponse, error)
}

func RegisterAdminServer(s *grpc.Server, srv AdminServer) {
	s.RegisterService(&_Admin_serviceDesc, srv)
}

func _Admin_Backups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).Backups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Admin/Backups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).Backups(ctx, req.(*BackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Admin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "admin.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Backups",
			Handler:    _Admin_Backups_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/admin/admin.proto",
}

func init() { proto.RegisterFile("server/admin/admin.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x4f, 0x4c, 0xc9, 0xcd, 0xcc, 0x83, 0x90, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9,
	0x42, 0xac, 0x60, 0x8e, 0x94, 0x4c, 0x71, 0x49, 0x62, 0x49, 0x69, 0xb1, 0x3e, 0x84, 0x2a, 0x48,
	0x82, 0x32, 0x20, 0x8a, 0x94, 0x04, 0xb8, 0xf8, 0x9c, 0x12, 0x93, 0xb3, 0x4b, 0x0b, 0x8a, 0x83,
	0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x94, 0x5c, 0xb9, 0xf8, 0xe1, 0x22, 0xc5, 0x05, 0xf9, 0x79,
	0xc5, 0xa9, 0x42, 0x46, 0x5c, 0xec, 0x49, 0x10, 0x21, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23,
	0x09, 0x3d, 0x88, 0x45, 0x10, 0x85, 0x9e, 0x79, 0x69, 0xf9, 0xe1, 0x99, 0x25, 0x19, 0xde, 0xa9,
	0x95, 0x41, 0x30, 0x85, 0x4a, 0xfe, 0x5c, 0x82, 0x18, 0xb2, 0x42, 0x02, 0x5c, 0xcc, 0xd9, 0xa9,
	0x95, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x20, 0xa6, 0x90, 0x06, 0x17, 0x4b, 0x66, 0x5e,
	0x5a, 0xbe, 0x04, 0x93, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0x88, 0x1e, 0xcc, 0x95, 0x48, 0x46, 0x07,
	0x81, 0x55, 0x18, 0x39, 0x73, 0xb1, 0x3a, 0x82, 0x2c, 0x15, 0xb2, 0xe2, 0x62, 0x87, 0x3a, 0x50,
	0x48, 0x14, 0xc5, 0x1d, 0x30, 0x2f, 0x48, 0x89, 0xa1, 0x0b, 0x43, 0xfc, 0xa1, 0xc4, 0x90, 0xc4,
	0x06, 0xf6, 0xb5, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x18, 0x1b, 0xe2, 0x36, 0x01, 0x00,
	0x00,
}
