// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage/storagepb/storage.proto

/*
Package storagepb is a generated protocol buffer package.

It is generated from these files:
	storage/storagepb/storage.proto

It has these top-level messages:
	GetLatestToLSNRequest
	GetLatestToLSNResponse
	GetKeysAtPointRequest
	GetKeysAtPointResponse
	BackupFileInfo
	GetFileByKeyRequest
	FileStream
*/
package storagepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetLatestToLSNRequest struct {
	Db string `protobuf:"bytes,1,opt,name=db" json:"db,omitempty"`
}

func (m *GetLatestToLSNRequest) Reset()                    { *m = GetLatestToLSNRequest{} }
func (m *GetLatestToLSNRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLatestToLSNRequest) ProtoMessage()               {}
func (*GetLatestToLSNRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetLatestToLSNRequest) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

type GetLatestToLSNResponse struct {
	Lsn string `protobuf:"bytes,1,opt,name=lsn" json:"lsn,omitempty"`
}

func (m *GetLatestToLSNResponse) Reset()                    { *m = GetLatestToLSNResponse{} }
func (m *GetLatestToLSNResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLatestToLSNResponse) ProtoMessage()               {}
func (*GetLatestToLSNResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetLatestToLSNResponse) GetLsn() string {
	if m != nil {
		return m.Lsn
	}
	return ""
}

type GetKeysAtPointRequest struct {
	Db   string `protobuf:"bytes,1,opt,name=db" json:"db,omitempty"`
	From string `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
}

func (m *GetKeysAtPointRequest) Reset()                    { *m = GetKeysAtPointRequest{} }
func (m *GetKeysAtPointRequest) String() string            { return proto.CompactTextString(m) }
func (*GetKeysAtPointRequest) ProtoMessage()               {}
func (*GetKeysAtPointRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetKeysAtPointRequest) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *GetKeysAtPointRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

type GetKeysAtPointResponse struct {
	Keys []*BackupFileInfo `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
}

func (m *GetKeysAtPointResponse) Reset()                    { *m = GetKeysAtPointResponse{} }
func (m *GetKeysAtPointResponse) String() string            { return proto.CompactTextString(m) }
func (*GetKeysAtPointResponse) ProtoMessage()               {}
func (*GetKeysAtPointResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetKeysAtPointResponse) GetKeys() []*BackupFileInfo {
	if m != nil {
		return m.Keys
	}
	return nil
}

type BackupFileInfo struct {
	StorageType string `protobuf:"bytes,1,opt,name=storage_type,json=storageType" json:"storage_type,omitempty"`
	BackupType  string `protobuf:"bytes,2,opt,name=backup_type,json=backupType" json:"backup_type,omitempty"`
	Key         string `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
}

func (m *BackupFileInfo) Reset()                    { *m = BackupFileInfo{} }
func (m *BackupFileInfo) String() string            { return proto.CompactTextString(m) }
func (*BackupFileInfo) ProtoMessage()               {}
func (*BackupFileInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BackupFileInfo) GetStorageType() string {
	if m != nil {
		return m.StorageType
	}
	return ""
}

func (m *BackupFileInfo) GetBackupType() string {
	if m != nil {
		return m.BackupType
	}
	return ""
}

func (m *BackupFileInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetFileByKeyRequest struct {
	Key         string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	StorageType string `protobuf:"bytes,2,opt,name=storage_type,json=storageType" json:"storage_type,omitempty"`
}

func (m *GetFileByKeyRequest) Reset()                    { *m = GetFileByKeyRequest{} }
func (m *GetFileByKeyRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFileByKeyRequest) ProtoMessage()               {}
func (*GetFileByKeyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetFileByKeyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetFileByKeyRequest) GetStorageType() string {
	if m != nil {
		return m.StorageType
	}
	return ""
}

type FileStream struct {
	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *FileStream) Reset()                    { *m = FileStream{} }
func (m *FileStream) String() string            { return proto.CompactTextString(m) }
func (*FileStream) ProtoMessage()               {}
func (*FileStream) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FileStream) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*GetLatestToLSNRequest)(nil), "storagepb.GetLatestToLSNRequest")
	proto.RegisterType((*GetLatestToLSNResponse)(nil), "storagepb.GetLatestToLSNResponse")
	proto.RegisterType((*GetKeysAtPointRequest)(nil), "storagepb.GetKeysAtPointRequest")
	proto.RegisterType((*GetKeysAtPointResponse)(nil), "storagepb.GetKeysAtPointResponse")
	proto.RegisterType((*BackupFileInfo)(nil), "storagepb.BackupFileInfo")
	proto.RegisterType((*GetFileByKeyRequest)(nil), "storagepb.GetFileByKeyRequest")
	proto.RegisterType((*FileStream)(nil), "storagepb.FileStream")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for StorageService service

type StorageServiceClient interface {
	GetLatestToLSN(ctx context.Context, in *GetLatestToLSNRequest, opts ...grpc.CallOption) (*GetLatestToLSNResponse, error)
	GetKeysAtPoint(ctx context.Context, in *GetKeysAtPointRequest, opts ...grpc.CallOption) (*GetKeysAtPointResponse, error)
	GetFileByKey(ctx context.Context, in *GetFileByKeyRequest, opts ...grpc.CallOption) (StorageService_GetFileByKeyClient, error)
}

type storageServiceClient struct {
	cc *grpc.ClientConn
}

func NewStorageServiceClient(cc *grpc.ClientConn) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) GetLatestToLSN(ctx context.Context, in *GetLatestToLSNRequest, opts ...grpc.CallOption) (*GetLatestToLSNResponse, error) {
	out := new(GetLatestToLSNResponse)
	err := grpc.Invoke(ctx, "/storagepb.StorageService/GetLatestToLSN", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetKeysAtPoint(ctx context.Context, in *GetKeysAtPointRequest, opts ...grpc.CallOption) (*GetKeysAtPointResponse, error) {
	out := new(GetKeysAtPointResponse)
	err := grpc.Invoke(ctx, "/storagepb.StorageService/GetKeysAtPoint", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetFileByKey(ctx context.Context, in *GetFileByKeyRequest, opts ...grpc.CallOption) (StorageService_GetFileByKeyClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_StorageService_serviceDesc.Streams[0], c.cc, "/storagepb.StorageService/GetFileByKey", opts...)
	if err != nil {
		return nil, err
	}
	x := &storageServiceGetFileByKeyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StorageService_GetFileByKeyClient interface {
	Recv() (*FileStream, error)
	grpc.ClientStream
}

type storageServiceGetFileByKeyClient struct {
	grpc.ClientStream
}

func (x *storageServiceGetFileByKeyClient) Recv() (*FileStream, error) {
	m := new(FileStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for StorageService service

type StorageServiceServer interface {
	GetLatestToLSN(context.Context, *GetLatestToLSNRequest) (*GetLatestToLSNResponse, error)
	GetKeysAtPoint(context.Context, *GetKeysAtPointRequest) (*GetKeysAtPointResponse, error)
	GetFileByKey(*GetFileByKeyRequest, StorageService_GetFileByKeyServer) error
}

func RegisterStorageServiceServer(s *grpc.Server, srv StorageServiceServer) {
	s.RegisterService(&_StorageService_serviceDesc, srv)
}

func _StorageService_GetLatestToLSN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestToLSNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetLatestToLSN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storagepb.StorageService/GetLatestToLSN",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetLatestToLSN(ctx, req.(*GetLatestToLSNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetKeysAtPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeysAtPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetKeysAtPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storagepb.StorageService/GetKeysAtPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetKeysAtPoint(ctx, req.(*GetKeysAtPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetFileByKey_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetFileByKeyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServiceServer).GetFileByKey(m, &storageServiceGetFileByKeyServer{stream})
}

type StorageService_GetFileByKeyServer interface {
	Send(*FileStream) error
	grpc.ServerStream
}

type storageServiceGetFileByKeyServer struct {
	grpc.ServerStream
}

func (x *storageServiceGetFileByKeyServer) Send(m *FileStream) error {
	return x.ServerStream.SendMsg(m)
}

var _StorageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storagepb.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestToLSN",
			Handler:    _StorageService_GetLatestToLSN_Handler,
		},
		{
			MethodName: "GetKeysAtPoint",
			Handler:    _StorageService_GetKeysAtPoint_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetFileByKey",
			Handler:       _StorageService_GetFileByKey_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "storage/storagepb/storage.proto",
}

func init() { proto.RegisterFile("storage/storagepb/storage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0xa5, 0x2d, 0xf9, 0xbe, 0x30, 0x90, 0x86, 0xac, 0xc1, 0x54, 0x0e, 0x02, 0x7b, 0x50, 0x62,
	0x22, 0x1a, 0x3c, 0x7a, 0x92, 0x83, 0x04, 0x21, 0xc6, 0xb4, 0x24, 0x1e, 0x4d, 0x0b, 0x83, 0x21,
	0x85, 0x6e, 0xed, 0x2e, 0x26, 0xfb, 0x23, 0xfc, 0xcf, 0x86, 0xed, 0x82, 0x6d, 0x41, 0x4f, 0x9d,
	0xce, 0xbe, 0x79, 0x6f, 0xe7, 0xbd, 0x85, 0x16, 0x17, 0x2c, 0xf1, 0xdf, 0xf1, 0x46, 0x7f, 0xe3,
	0x60, 0x57, 0xf5, 0xe2, 0x84, 0x09, 0x46, 0x2a, 0xfb, 0x03, 0x7a, 0x09, 0x8d, 0x21, 0x8a, 0x89,
	0x2f, 0x90, 0x8b, 0x29, 0x9b, 0x78, 0xcf, 0x2e, 0x7e, 0x6c, 0x90, 0x0b, 0x62, 0x83, 0x39, 0x0f,
	0x1c, 0xa3, 0x6d, 0x74, 0x2b, 0xae, 0x39, 0x0f, 0xe8, 0x15, 0x9c, 0x16, 0x81, 0x3c, 0x66, 0x11,
	0x47, 0x52, 0x07, 0x6b, 0xc5, 0x23, 0x0d, 0xdd, 0x96, 0xf4, 0x5e, 0x91, 0x8e, 0x51, 0xf2, 0x07,
	0xf1, 0xc2, 0x96, 0x91, 0xf8, 0x85, 0x94, 0x10, 0x28, 0x2f, 0x12, 0xb6, 0x76, 0x4c, 0xd5, 0x51,
	0x35, 0x1d, 0x2a, 0xa1, 0xdc, 0xb0, 0x16, 0xba, 0x86, 0x72, 0x88, 0x92, 0x3b, 0x46, 0xdb, 0xea,
	0x56, 0xfb, 0x67, 0xbd, 0xfd, 0x16, 0xbd, 0x81, 0x3f, 0x0b, 0x37, 0xf1, 0xe3, 0x72, 0x85, 0xa3,
	0x68, 0xc1, 0x5c, 0x05, 0xa3, 0x0b, 0xb0, 0xf3, 0x7d, 0xd2, 0x81, 0x9a, 0x9e, 0x79, 0x13, 0x32,
	0x46, 0x7d, 0x91, 0xaa, 0xee, 0x4d, 0x65, 0x8c, 0xa4, 0x05, 0xd5, 0x40, 0x0d, 0xa5, 0x88, 0xf4,
	0x62, 0x90, 0xb6, 0x14, 0xa0, 0x0e, 0x56, 0x88, 0xd2, 0xb1, 0xd2, 0x6d, 0x43, 0x94, 0xf4, 0x09,
	0x4e, 0x86, 0x28, 0xb6, 0x22, 0x03, 0x39, 0x46, 0xb9, 0xdb, 0x55, 0x03, 0x8d, 0x3d, 0xf0, 0x40,
	0xde, 0x3c, 0x90, 0xa7, 0x17, 0x00, 0x5b, 0x22, 0x4f, 0x24, 0xe8, 0xaf, 0x89, 0x03, 0xff, 0x67,
	0x2c, 0x12, 0x18, 0x09, 0x45, 0x53, 0x73, 0x77, 0xbf, 0xfd, 0x2f, 0x13, 0x6c, 0x2f, 0x9d, 0xf3,
	0x30, 0xf9, 0x5c, 0xce, 0x90, 0xbc, 0x82, 0x9d, 0x0f, 0x88, 0xb4, 0x33, 0x0e, 0x1d, 0x0d, 0xb9,
	0xd9, 0xf9, 0x03, 0x91, 0x9a, 0x4e, 0x4b, 0x9a, 0x38, 0x13, 0x48, 0x91, 0xf8, 0x30, 0xe8, 0x22,
	0xf1, 0x91, 0x34, 0x69, 0x89, 0x8c, 0xa0, 0x96, 0x35, 0x8e, 0x9c, 0xe7, 0x87, 0x8a, 0x8e, 0x36,
	0x1b, 0x99, 0xf3, 0x1f, 0x97, 0x68, 0xe9, 0xd6, 0x08, 0xfe, 0xa9, 0x87, 0x7d, 0xf7, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0x42, 0x60, 0x42, 0x73, 0xfb, 0x02, 0x00, 0x00,
}
