// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage/storagepb/storage.proto

/*
Package storagepb is a generated protocol buffer package.

It is generated from these files:
	storage/storagepb/storage.proto

It has these top-level messages:
	GetLatestToLSNRequest
	GetLatestToLSNResponse
	GetKeysAtPointRequest
	GetKeysAtPointResponse
	BackupFileInfo
	GetFileByKeyRequest
	FileStream
	PurgePrevBackupRequest
	PurgePrevBackupResponse
	FullBackupContentStream
	IncBackupContentStream
	BackupReply
	PostCheckpointsRequest
	PostCheckpointsResponse
*/
package storagepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetLatestToLSNRequest struct {
	Db string `protobuf:"bytes,1,opt,name=db" json:"db,omitempty"`
}

func (m *GetLatestToLSNRequest) Reset()                    { *m = GetLatestToLSNRequest{} }
func (m *GetLatestToLSNRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLatestToLSNRequest) ProtoMessage()               {}
func (*GetLatestToLSNRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetLatestToLSNRequest) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

type GetLatestToLSNResponse struct {
	Lsn string `protobuf:"bytes,1,opt,name=lsn" json:"lsn,omitempty"`
}

func (m *GetLatestToLSNResponse) Reset()                    { *m = GetLatestToLSNResponse{} }
func (m *GetLatestToLSNResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLatestToLSNResponse) ProtoMessage()               {}
func (*GetLatestToLSNResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetLatestToLSNResponse) GetLsn() string {
	if m != nil {
		return m.Lsn
	}
	return ""
}

type GetKeysAtPointRequest struct {
	Db   string `protobuf:"bytes,1,opt,name=db" json:"db,omitempty"`
	From string `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
}

func (m *GetKeysAtPointRequest) Reset()                    { *m = GetKeysAtPointRequest{} }
func (m *GetKeysAtPointRequest) String() string            { return proto.CompactTextString(m) }
func (*GetKeysAtPointRequest) ProtoMessage()               {}
func (*GetKeysAtPointRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetKeysAtPointRequest) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *GetKeysAtPointRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

type GetKeysAtPointResponse struct {
	Keys []*BackupFileInfo `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
}

func (m *GetKeysAtPointResponse) Reset()                    { *m = GetKeysAtPointResponse{} }
func (m *GetKeysAtPointResponse) String() string            { return proto.CompactTextString(m) }
func (*GetKeysAtPointResponse) ProtoMessage()               {}
func (*GetKeysAtPointResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetKeysAtPointResponse) GetKeys() []*BackupFileInfo {
	if m != nil {
		return m.Keys
	}
	return nil
}

type BackupFileInfo struct {
	StorageType string `protobuf:"bytes,1,opt,name=storage_type,json=storageType" json:"storage_type,omitempty"`
	BackupType  string `protobuf:"bytes,2,opt,name=backup_type,json=backupType" json:"backup_type,omitempty"`
	Key         string `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	Size        int64  `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
}

func (m *BackupFileInfo) Reset()                    { *m = BackupFileInfo{} }
func (m *BackupFileInfo) String() string            { return proto.CompactTextString(m) }
func (*BackupFileInfo) ProtoMessage()               {}
func (*BackupFileInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BackupFileInfo) GetStorageType() string {
	if m != nil {
		return m.StorageType
	}
	return ""
}

func (m *BackupFileInfo) GetBackupType() string {
	if m != nil {
		return m.BackupType
	}
	return ""
}

func (m *BackupFileInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *BackupFileInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type GetFileByKeyRequest struct {
	Key         string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	StorageType string `protobuf:"bytes,2,opt,name=storage_type,json=storageType" json:"storage_type,omitempty"`
}

func (m *GetFileByKeyRequest) Reset()                    { *m = GetFileByKeyRequest{} }
func (m *GetFileByKeyRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFileByKeyRequest) ProtoMessage()               {}
func (*GetFileByKeyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetFileByKeyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetFileByKeyRequest) GetStorageType() string {
	if m != nil {
		return m.StorageType
	}
	return ""
}

type FileStream struct {
	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *FileStream) Reset()                    { *m = FileStream{} }
func (m *FileStream) String() string            { return proto.CompactTextString(m) }
func (*FileStream) ProtoMessage()               {}
func (*FileStream) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FileStream) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type PurgePrevBackupRequest struct {
	Db string `protobuf:"bytes,1,opt,name=db" json:"db,omitempty"`
}

func (m *PurgePrevBackupRequest) Reset()                    { *m = PurgePrevBackupRequest{} }
func (m *PurgePrevBackupRequest) String() string            { return proto.CompactTextString(m) }
func (*PurgePrevBackupRequest) ProtoMessage()               {}
func (*PurgePrevBackupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PurgePrevBackupRequest) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

type PurgePrevBackupResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *PurgePrevBackupResponse) Reset()                    { *m = PurgePrevBackupResponse{} }
func (m *PurgePrevBackupResponse) String() string            { return proto.CompactTextString(m) }
func (*PurgePrevBackupResponse) ProtoMessage()               {}
func (*PurgePrevBackupResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PurgePrevBackupResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FullBackupContentStream struct {
	Db      string `protobuf:"bytes,1,opt,name=db" json:"db,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *FullBackupContentStream) Reset()                    { *m = FullBackupContentStream{} }
func (m *FullBackupContentStream) String() string            { return proto.CompactTextString(m) }
func (*FullBackupContentStream) ProtoMessage()               {}
func (*FullBackupContentStream) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *FullBackupContentStream) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *FullBackupContentStream) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type IncBackupContentStream struct {
	Db      string `protobuf:"bytes,1,opt,name=db" json:"db,omitempty"`
	Lsn     string `protobuf:"bytes,2,opt,name=lsn" json:"lsn,omitempty"`
	Content []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *IncBackupContentStream) Reset()                    { *m = IncBackupContentStream{} }
func (m *IncBackupContentStream) String() string            { return proto.CompactTextString(m) }
func (*IncBackupContentStream) ProtoMessage()               {}
func (*IncBackupContentStream) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *IncBackupContentStream) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *IncBackupContentStream) GetLsn() string {
	if m != nil {
		return m.Lsn
	}
	return ""
}

func (m *IncBackupContentStream) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type BackupReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Key     string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *BackupReply) Reset()                    { *m = BackupReply{} }
func (m *BackupReply) String() string            { return proto.CompactTextString(m) }
func (*BackupReply) ProtoMessage()               {}
func (*BackupReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *BackupReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BackupReply) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type PostCheckpointsRequest struct {
	Key     string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *PostCheckpointsRequest) Reset()                    { *m = PostCheckpointsRequest{} }
func (m *PostCheckpointsRequest) String() string            { return proto.CompactTextString(m) }
func (*PostCheckpointsRequest) ProtoMessage()               {}
func (*PostCheckpointsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *PostCheckpointsRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PostCheckpointsRequest) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type PostCheckpointsResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *PostCheckpointsResponse) Reset()                    { *m = PostCheckpointsResponse{} }
func (m *PostCheckpointsResponse) String() string            { return proto.CompactTextString(m) }
func (*PostCheckpointsResponse) ProtoMessage()               {}
func (*PostCheckpointsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *PostCheckpointsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GetLatestToLSNRequest)(nil), "storagepb.GetLatestToLSNRequest")
	proto.RegisterType((*GetLatestToLSNResponse)(nil), "storagepb.GetLatestToLSNResponse")
	proto.RegisterType((*GetKeysAtPointRequest)(nil), "storagepb.GetKeysAtPointRequest")
	proto.RegisterType((*GetKeysAtPointResponse)(nil), "storagepb.GetKeysAtPointResponse")
	proto.RegisterType((*BackupFileInfo)(nil), "storagepb.BackupFileInfo")
	proto.RegisterType((*GetFileByKeyRequest)(nil), "storagepb.GetFileByKeyRequest")
	proto.RegisterType((*FileStream)(nil), "storagepb.FileStream")
	proto.RegisterType((*PurgePrevBackupRequest)(nil), "storagepb.PurgePrevBackupRequest")
	proto.RegisterType((*PurgePrevBackupResponse)(nil), "storagepb.PurgePrevBackupResponse")
	proto.RegisterType((*FullBackupContentStream)(nil), "storagepb.FullBackupContentStream")
	proto.RegisterType((*IncBackupContentStream)(nil), "storagepb.IncBackupContentStream")
	proto.RegisterType((*BackupReply)(nil), "storagepb.BackupReply")
	proto.RegisterType((*PostCheckpointsRequest)(nil), "storagepb.PostCheckpointsRequest")
	proto.RegisterType((*PostCheckpointsResponse)(nil), "storagepb.PostCheckpointsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for StorageService service

type StorageServiceClient interface {
	GetLatestToLSN(ctx context.Context, in *GetLatestToLSNRequest, opts ...grpc.CallOption) (*GetLatestToLSNResponse, error)
	GetKeysAtPoint(ctx context.Context, in *GetKeysAtPointRequest, opts ...grpc.CallOption) (*GetKeysAtPointResponse, error)
	GetFileByKey(ctx context.Context, in *GetFileByKeyRequest, opts ...grpc.CallOption) (StorageService_GetFileByKeyClient, error)
	PurgePrevBackup(ctx context.Context, in *PurgePrevBackupRequest, opts ...grpc.CallOption) (*PurgePrevBackupResponse, error)
	TransferFullBackup(ctx context.Context, opts ...grpc.CallOption) (StorageService_TransferFullBackupClient, error)
	TransferIncBackup(ctx context.Context, opts ...grpc.CallOption) (StorageService_TransferIncBackupClient, error)
	PostCheckpoints(ctx context.Context, in *PostCheckpointsRequest, opts ...grpc.CallOption) (*PostCheckpointsResponse, error)
}

type storageServiceClient struct {
	cc *grpc.ClientConn
}

func NewStorageServiceClient(cc *grpc.ClientConn) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) GetLatestToLSN(ctx context.Context, in *GetLatestToLSNRequest, opts ...grpc.CallOption) (*GetLatestToLSNResponse, error) {
	out := new(GetLatestToLSNResponse)
	err := grpc.Invoke(ctx, "/storagepb.StorageService/GetLatestToLSN", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetKeysAtPoint(ctx context.Context, in *GetKeysAtPointRequest, opts ...grpc.CallOption) (*GetKeysAtPointResponse, error) {
	out := new(GetKeysAtPointResponse)
	err := grpc.Invoke(ctx, "/storagepb.StorageService/GetKeysAtPoint", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetFileByKey(ctx context.Context, in *GetFileByKeyRequest, opts ...grpc.CallOption) (StorageService_GetFileByKeyClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_StorageService_serviceDesc.Streams[0], c.cc, "/storagepb.StorageService/GetFileByKey", opts...)
	if err != nil {
		return nil, err
	}
	x := &storageServiceGetFileByKeyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StorageService_GetFileByKeyClient interface {
	Recv() (*FileStream, error)
	grpc.ClientStream
}

type storageServiceGetFileByKeyClient struct {
	grpc.ClientStream
}

func (x *storageServiceGetFileByKeyClient) Recv() (*FileStream, error) {
	m := new(FileStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageServiceClient) PurgePrevBackup(ctx context.Context, in *PurgePrevBackupRequest, opts ...grpc.CallOption) (*PurgePrevBackupResponse, error) {
	out := new(PurgePrevBackupResponse)
	err := grpc.Invoke(ctx, "/storagepb.StorageService/PurgePrevBackup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) TransferFullBackup(ctx context.Context, opts ...grpc.CallOption) (StorageService_TransferFullBackupClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_StorageService_serviceDesc.Streams[1], c.cc, "/storagepb.StorageService/TransferFullBackup", opts...)
	if err != nil {
		return nil, err
	}
	x := &storageServiceTransferFullBackupClient{stream}
	return x, nil
}

type StorageService_TransferFullBackupClient interface {
	Send(*FullBackupContentStream) error
	CloseAndRecv() (*BackupReply, error)
	grpc.ClientStream
}

type storageServiceTransferFullBackupClient struct {
	grpc.ClientStream
}

func (x *storageServiceTransferFullBackupClient) Send(m *FullBackupContentStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storageServiceTransferFullBackupClient) CloseAndRecv() (*BackupReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(BackupReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageServiceClient) TransferIncBackup(ctx context.Context, opts ...grpc.CallOption) (StorageService_TransferIncBackupClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_StorageService_serviceDesc.Streams[2], c.cc, "/storagepb.StorageService/TransferIncBackup", opts...)
	if err != nil {
		return nil, err
	}
	x := &storageServiceTransferIncBackupClient{stream}
	return x, nil
}

type StorageService_TransferIncBackupClient interface {
	Send(*IncBackupContentStream) error
	CloseAndRecv() (*BackupReply, error)
	grpc.ClientStream
}

type storageServiceTransferIncBackupClient struct {
	grpc.ClientStream
}

func (x *storageServiceTransferIncBackupClient) Send(m *IncBackupContentStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storageServiceTransferIncBackupClient) CloseAndRecv() (*BackupReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(BackupReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageServiceClient) PostCheckpoints(ctx context.Context, in *PostCheckpointsRequest, opts ...grpc.CallOption) (*PostCheckpointsResponse, error) {
	out := new(PostCheckpointsResponse)
	err := grpc.Invoke(ctx, "/storagepb.StorageService/PostCheckpoints", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StorageService service

type StorageServiceServer interface {
	GetLatestToLSN(context.Context, *GetLatestToLSNRequest) (*GetLatestToLSNResponse, error)
	GetKeysAtPoint(context.Context, *GetKeysAtPointRequest) (*GetKeysAtPointResponse, error)
	GetFileByKey(*GetFileByKeyRequest, StorageService_GetFileByKeyServer) error
	PurgePrevBackup(context.Context, *PurgePrevBackupRequest) (*PurgePrevBackupResponse, error)
	TransferFullBackup(StorageService_TransferFullBackupServer) error
	TransferIncBackup(StorageService_TransferIncBackupServer) error
	PostCheckpoints(context.Context, *PostCheckpointsRequest) (*PostCheckpointsResponse, error)
}

func RegisterStorageServiceServer(s *grpc.Server, srv StorageServiceServer) {
	s.RegisterService(&_StorageService_serviceDesc, srv)
}

func _StorageService_GetLatestToLSN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestToLSNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetLatestToLSN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storagepb.StorageService/GetLatestToLSN",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetLatestToLSN(ctx, req.(*GetLatestToLSNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetKeysAtPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeysAtPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetKeysAtPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storagepb.StorageService/GetKeysAtPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetKeysAtPoint(ctx, req.(*GetKeysAtPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetFileByKey_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetFileByKeyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServiceServer).GetFileByKey(m, &storageServiceGetFileByKeyServer{stream})
}

type StorageService_GetFileByKeyServer interface {
	Send(*FileStream) error
	grpc.ServerStream
}

type storageServiceGetFileByKeyServer struct {
	grpc.ServerStream
}

func (x *storageServiceGetFileByKeyServer) Send(m *FileStream) error {
	return x.ServerStream.SendMsg(m)
}

func _StorageService_PurgePrevBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgePrevBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).PurgePrevBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storagepb.StorageService/PurgePrevBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).PurgePrevBackup(ctx, req.(*PurgePrevBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_TransferFullBackup_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageServiceServer).TransferFullBackup(&storageServiceTransferFullBackupServer{stream})
}

type StorageService_TransferFullBackupServer interface {
	SendAndClose(*BackupReply) error
	Recv() (*FullBackupContentStream, error)
	grpc.ServerStream
}

type storageServiceTransferFullBackupServer struct {
	grpc.ServerStream
}

func (x *storageServiceTransferFullBackupServer) SendAndClose(m *BackupReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storageServiceTransferFullBackupServer) Recv() (*FullBackupContentStream, error) {
	m := new(FullBackupContentStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StorageService_TransferIncBackup_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageServiceServer).TransferIncBackup(&storageServiceTransferIncBackupServer{stream})
}

type StorageService_TransferIncBackupServer interface {
	SendAndClose(*BackupReply) error
	Recv() (*IncBackupContentStream, error)
	grpc.ServerStream
}

type storageServiceTransferIncBackupServer struct {
	grpc.ServerStream
}

func (x *storageServiceTransferIncBackupServer) SendAndClose(m *BackupReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storageServiceTransferIncBackupServer) Recv() (*IncBackupContentStream, error) {
	m := new(IncBackupContentStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StorageService_PostCheckpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCheckpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).PostCheckpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storagepb.StorageService/PostCheckpoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).PostCheckpoints(ctx, req.(*PostCheckpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storagepb.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestToLSN",
			Handler:    _StorageService_GetLatestToLSN_Handler,
		},
		{
			MethodName: "GetKeysAtPoint",
			Handler:    _StorageService_GetKeysAtPoint_Handler,
		},
		{
			MethodName: "PurgePrevBackup",
			Handler:    _StorageService_PurgePrevBackup_Handler,
		},
		{
			MethodName: "PostCheckpoints",
			Handler:    _StorageService_PostCheckpoints_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetFileByKey",
			Handler:       _StorageService_GetFileByKey_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TransferFullBackup",
			Handler:       _StorageService_TransferFullBackup_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "TransferIncBackup",
			Handler:       _StorageService_TransferIncBackup_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "storage/storagepb/storage.proto",
}

func init() { proto.RegisterFile("storage/storagepb/storage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 566 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xd1, 0x6e, 0xda, 0x30,
	0x14, 0x25, 0x09, 0x5a, 0xd5, 0x0b, 0x62, 0x9d, 0xa7, 0xd2, 0x8c, 0x87, 0x95, 0xfa, 0x61, 0x43,
	0x93, 0xc6, 0xa6, 0xf6, 0x69, 0xda, 0xd3, 0xca, 0x54, 0xc4, 0x5a, 0x4d, 0x28, 0x20, 0x4d, 0xda,
	0xcb, 0x14, 0xe8, 0x85, 0x21, 0x42, 0x9c, 0xc5, 0xa6, 0x52, 0xfa, 0xd3, 0xfb, 0x85, 0x29, 0x8e,
	0x13, 0xe2, 0x90, 0xb0, 0x3e, 0xc5, 0x71, 0xce, 0x3d, 0x3e, 0xf7, 0xf8, 0xdc, 0xc0, 0x39, 0x17,
	0x2c, 0x74, 0x97, 0xf8, 0x41, 0x3d, 0x83, 0x59, 0xba, 0xea, 0x07, 0x21, 0x13, 0x8c, 0x1c, 0x67,
	0x1f, 0xe8, 0x5b, 0x38, 0x1d, 0xa2, 0xb8, 0x73, 0x05, 0x72, 0x31, 0x65, 0x77, 0x93, 0xef, 0x0e,
	0xfe, 0xd9, 0x22, 0x17, 0xa4, 0x05, 0xe6, 0xfd, 0xcc, 0x36, 0xba, 0x46, 0xef, 0xd8, 0x31, 0xef,
	0x67, 0xf4, 0x1d, 0xb4, 0x8b, 0x40, 0x1e, 0x30, 0x9f, 0x23, 0x39, 0x01, 0xcb, 0xe3, 0xbe, 0x82,
	0xc6, 0x4b, 0xfa, 0x59, 0x92, 0xde, 0x62, 0xc4, 0xbf, 0x88, 0x31, 0x5b, 0xf9, 0xa2, 0x82, 0x94,
	0x10, 0xa8, 0x2f, 0x42, 0xb6, 0xb1, 0x4d, 0xb9, 0x23, 0xd7, 0x74, 0x28, 0x0f, 0xd2, 0x8a, 0xd5,
	0x41, 0xef, 0xa1, 0xbe, 0xc6, 0x88, 0xdb, 0x46, 0xd7, 0xea, 0x35, 0x2e, 0x5f, 0xf5, 0xb3, 0x2e,
	0xfa, 0xd7, 0xee, 0x7c, 0xbd, 0x0d, 0x6e, 0x56, 0x1e, 0x8e, 0xfc, 0x05, 0x73, 0x24, 0x8c, 0x3e,
	0x42, 0x4b, 0xdf, 0x27, 0x17, 0xd0, 0x54, 0x35, 0xbf, 0x44, 0x14, 0xa0, 0x12, 0xd2, 0x50, 0x7b,
	0xd3, 0x28, 0x40, 0x72, 0x0e, 0x8d, 0x99, 0x2c, 0x4a, 0x10, 0x89, 0x30, 0x48, 0xb6, 0x24, 0xe0,
	0x04, 0xac, 0x35, 0x46, 0xb6, 0x95, 0x74, 0xbb, 0xc6, 0x28, 0x6e, 0x82, 0xaf, 0x1e, 0xd1, 0xae,
	0x77, 0x8d, 0x9e, 0xe5, 0xc8, 0x35, 0xfd, 0x06, 0x2f, 0x87, 0x28, 0xe2, 0x83, 0xaf, 0xa3, 0x5b,
	0x8c, 0xd2, 0xfe, 0x55, 0xb1, 0xb1, 0x2b, 0x2e, 0x4a, 0x32, 0xf7, 0x24, 0xd1, 0x37, 0x00, 0x31,
	0xd1, 0x44, 0x84, 0xe8, 0x6e, 0x88, 0x0d, 0x47, 0x73, 0xe6, 0x0b, 0xf4, 0x85, 0xa4, 0x69, 0x3a,
	0xe9, 0x2b, 0xed, 0x41, 0x7b, 0xbc, 0x0d, 0x97, 0x38, 0x0e, 0xf1, 0x21, 0x69, 0xbc, 0xea, 0x2e,
	0xaf, 0xe0, 0x6c, 0x0f, 0xa9, 0x3c, 0xb6, 0xe1, 0x68, 0x83, 0x9c, 0xbb, 0xcb, 0xd4, 0x9d, 0xf4,
	0x95, 0x0e, 0xe0, 0xec, 0x66, 0xeb, 0x79, 0x09, 0x7e, 0x90, 0x9c, 0xa9, 0x34, 0x15, 0xaf, 0x35,
	0xa7, 0xd1, 0xd4, 0x35, 0x4e, 0xa1, 0x3d, 0xf2, 0xe7, 0x4f, 0xe1, 0x50, 0xa9, 0x32, 0xb3, 0x54,
	0xe5, 0x59, 0x2d, 0x9d, 0xf5, 0x13, 0x34, 0xd2, 0x36, 0x02, 0x2f, 0xaa, 0xee, 0x21, 0xf5, 0xdf,
	0xcc, 0xfc, 0xa7, 0x5f, 0xa1, 0x3d, 0x66, 0x5c, 0x0c, 0x7e, 0xe3, 0x7c, 0x1d, 0xc4, 0x69, 0xe3,
	0xd5, 0x77, 0x55, 0xdd, 0x56, 0x6c, 0x68, 0x91, 0xe5, 0x7f, 0x86, 0x5e, 0xfe, 0xad, 0x43, 0x6b,
	0x92, 0xdc, 0xf3, 0x04, 0xc3, 0x87, 0xd5, 0x1c, 0xc9, 0x0f, 0x68, 0xe9, 0x43, 0x46, 0xba, 0xb9,
	0x94, 0x97, 0x0e, 0x6a, 0xe7, 0xe2, 0x00, 0x22, 0xd1, 0x40, 0x6b, 0x8a, 0x38, 0x37, 0x54, 0x45,
	0xe2, 0xfd, 0x61, 0x2d, 0x12, 0x97, 0x4c, 0x24, 0xad, 0x91, 0x11, 0x34, 0xf3, 0x41, 0x27, 0xaf,
	0xf5, 0xa2, 0xe2, 0x04, 0x74, 0x4e, 0x73, 0xdf, 0x77, 0xa9, 0xa6, 0xb5, 0x8f, 0x06, 0xf9, 0x09,
	0xcf, 0x0b, 0xa9, 0x24, 0x79, 0x09, 0xe5, 0xd9, 0xee, 0xd0, 0x43, 0x90, 0x4c, 0xe6, 0x14, 0xc8,
	0x34, 0x74, 0x7d, 0xbe, 0xc0, 0x70, 0x17, 0x62, 0x92, 0xaf, 0xad, 0xc8, 0x76, 0xa7, 0xbd, 0xf7,
	0x9b, 0x91, 0x21, 0xa3, 0xb5, 0x9e, 0x41, 0x1c, 0x78, 0x91, 0xb2, 0x66, 0xa9, 0xd6, 0x34, 0x97,
	0x67, 0xfd, 0x20, 0x67, 0xec, 0x82, 0x1e, 0x25, 0xdd, 0x85, 0xd2, 0xb0, 0xea, 0x2e, 0x94, 0x27,
	0x91, 0xd6, 0x66, 0xcf, 0xe4, 0xef, 0xff, 0xea, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76, 0x4a,
	0xfb, 0x1d, 0x21, 0x06, 0x00, 0x00,
}
