FROM buildpack-deps:xenial-scm

MAINTAINER Takuya Kuwahara <taakuu19@gmail.com>

# Make sure apt-get is up to date and dependent packages are installed
RUN \
  apt-get update && \
  apt-get install -y make libaio1 \
    --no-install-recommends

# Setup MySQL Sandbox
ENV SANDBOX_AS_ROOT 1
RUN \
  wget -q http://search.cpan.org/CPAN/authors/id/G/GM/GMAX/MySQL-Sandbox-3.2.10.tar.gz && \
  tar zxf MySQL-Sandbox-3.2.10.tar.gz && \
  cd MySQL-Sandbox-3.2.10 && \
  perl Makefile.PL && make && make install && \
  mkdir /sandbox && cd /sandbox && \
  wget -q https://downloads.mysql.com/archives/get/file/mysql-5.6.35-linux-glibc2.5-x86_64.tar.gz && \
  make_replication_sandbox --how_many_nodes=1 mysql-5.6.35-linux-glibc2.5-x86_64.tar.gz && \
  rm mysql-5.6.35-linux-glibc2.5-x86_64.tar.gz

# Install go 1.8.3
RUN \
  wget -q https://golang.org/dl/go1.8.3.linux-amd64.tar.gz && \
  tar -C /usr/local -xzf `basename https://golang.org/dl/go1.8.3.linux-amd64.tar.gz` && \
  rm /go1.8.3.linux-amd64.tar.gz
ENV PATH   /go/bin:/usr/local/go/bin:$PATH
ENV GOPATH /go
ENV GOROOT /usr/local/go

# Install Xtrabackup 2.3.8
RUN \
  wget -q https://repo.percona.com/apt/percona-release_0.1-4.xenial_all.deb && \
  dpkg -i percona-release_0.1-4.xenial_all.deb && \
  apt-get update && \
  apt-get install -y percona-xtrabackup=2.3.8-1.xenial

ENV PKG github.com/taku-k/polymerase
WORKDIR /go/src/$PKG
ADD pkg /go/src/$PKG/pkg
ADD vendor /go/src/$PKG/vendor
ADD Makefile main.go /go/src/$PKG/
RUN go install

ADD integration-test/sut/run.sh /
