// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: polypb/metadata.proto

/*
	Package polypb is a generated protocol buffer package.

	It is generated from these files:
		polypb/metadata.proto

	It has these top-level messages:
		DiskMeta
		NodeMeta
		BackupMeta
		XtrabackupMeta
		MysqldumpMeta
		XtrabackupCheckpoints
*/
package polypb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/gogo/protobuf/gogoproto"

import time "time"

import github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// StorageType
type StorageType int32

const (
	StorageType_LOCAL_DISK StorageType = 0
	StorageType_LOCAL_MEM  StorageType = 1
)

var StorageType_name = map[int32]string{
	0: "LOCAL_DISK",
	1: "LOCAL_MEM",
}
var StorageType_value = map[string]int32{
	"LOCAL_DISK": 0,
	"LOCAL_MEM":  1,
}

func (x StorageType) String() string {
	return proto.EnumName(StorageType_name, int32(x))
}
func (StorageType) EnumDescriptor() ([]byte, []int) { return fileDescriptorMetadata, []int{0} }

// BackupType
type BackupType int32

const (
	BackupType_XTRABACKUP_FULL BackupType = 0
	BackupType_XTRABACKUP_INC  BackupType = 1
	BackupType_MYSQLDUMP       BackupType = 2
)

var BackupType_name = map[int32]string{
	0: "XTRABACKUP_FULL",
	1: "XTRABACKUP_INC",
	2: "MYSQLDUMP",
}
var BackupType_value = map[string]int32{
	"XTRABACKUP_FULL": 0,
	"XTRABACKUP_INC":  1,
	"MYSQLDUMP":       2,
}

func (x BackupType) String() string {
	return proto.EnumName(BackupType_name, int32(x))
}
func (BackupType) EnumDescriptor() ([]byte, []int) { return fileDescriptorMetadata, []int{1} }

// DiskMeta is a metadata about a disk.
type DiskMeta struct {
	Total uint64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Avail uint64 `protobuf:"varint,2,opt,name=avail,proto3" json:"avail,omitempty"`
}

func (m *DiskMeta) Reset()                    { *m = DiskMeta{} }
func (m *DiskMeta) String() string            { return proto.CompactTextString(m) }
func (*DiskMeta) ProtoMessage()               {}
func (*DiskMeta) Descriptor() ([]byte, []int) { return fileDescriptorMetadata, []int{0} }

func (m *DiskMeta) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *DiskMeta) GetAvail() uint64 {
	if m != nil {
		return m.Avail
	}
	return 0
}

// NodeMeta is a metadata about a node.
type NodeMeta struct {
	Disk     *DiskMeta `protobuf:"bytes,1,opt,name=disk" json:"disk,omitempty"`
	Addr     string    `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	StoreDir string    `protobuf:"bytes,3,opt,name=store_dir,json=storeDir,proto3" json:"store_dir,omitempty"`
	NodeId   NodeID    `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3,casttype=NodeID" json:"node_id,omitempty"`
}

func (m *NodeMeta) Reset()                    { *m = NodeMeta{} }
func (m *NodeMeta) String() string            { return proto.CompactTextString(m) }
func (*NodeMeta) ProtoMessage()               {}
func (*NodeMeta) Descriptor() ([]byte, []int) { return fileDescriptorMetadata, []int{1} }

func (m *NodeMeta) GetDisk() *DiskMeta {
	if m != nil {
		return m.Disk
	}
	return nil
}

func (m *NodeMeta) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *NodeMeta) GetStoreDir() string {
	if m != nil {
		return m.StoreDir
	}
	return ""
}

func (m *NodeMeta) GetNodeId() NodeID {
	if m != nil {
		return m.NodeId
	}
	return nil
}

// BackupMeta is a metadata about a backup file.
type BackupMeta struct {
	StoredTime  *time.Time  `protobuf:"bytes,1,opt,name=stored_time,json=storedTime,stdtime" json:"stored_time,omitempty"`
	NodeId      NodeID      `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3,casttype=NodeID" json:"node_id,omitempty"`
	Host        string      `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	StorageType StorageType `protobuf:"varint,4,opt,name=storage_type,json=storageType,proto3,enum=polypb.StorageType" json:"storage_type,omitempty"`
	EndTime     *time.Time  `protobuf:"bytes,5,opt,name=end_time,json=endTime,stdtime" json:"end_time,omitempty"`
	FileSize    int64       `protobuf:"varint,6,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	BackupType  BackupType  `protobuf:"varint,7,opt,name=backup_type,json=backupType,proto3,enum=polypb.BackupType" json:"backup_type,omitempty"`
	Db          DatabaseID  `protobuf:"bytes,8,opt,name=db,proto3,casttype=DatabaseID" json:"db,omitempty"`
	//  string to_lsn = 9;
	Key           Key       `protobuf:"bytes,10,opt,name=key,proto3,casttype=Key" json:"key,omitempty"`
	BaseTimePoint TimePoint `protobuf:"bytes,11,opt,name=base_time_point,json=baseTimePoint,proto3,casttype=TimePoint" json:"base_time_point,omitempty"`
	// Types that are valid to be assigned to Details:
	//	*BackupMeta_Xtrabackup
	//	*BackupMeta_Mysqldump
	Details isBackupMeta_Details `protobuf_oneof:"details"`
}

func (m *BackupMeta) Reset()                    { *m = BackupMeta{} }
func (m *BackupMeta) String() string            { return proto.CompactTextString(m) }
func (*BackupMeta) ProtoMessage()               {}
func (*BackupMeta) Descriptor() ([]byte, []int) { return fileDescriptorMetadata, []int{2} }

type isBackupMeta_Details interface {
	isBackupMeta_Details()
	MarshalTo([]byte) (int, error)
	Size() int
}

type BackupMeta_Xtrabackup struct {
	Xtrabackup *XtrabackupMeta `protobuf:"bytes,12,opt,name=xtrabackup,oneof"`
}
type BackupMeta_Mysqldump struct {
	Mysqldump *MysqldumpMeta `protobuf:"bytes,13,opt,name=mysqldump,oneof"`
}

func (*BackupMeta_Xtrabackup) isBackupMeta_Details() {}
func (*BackupMeta_Mysqldump) isBackupMeta_Details()  {}

func (m *BackupMeta) GetDetails() isBackupMeta_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *BackupMeta) GetStoredTime() *time.Time {
	if m != nil {
		return m.StoredTime
	}
	return nil
}

func (m *BackupMeta) GetNodeId() NodeID {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *BackupMeta) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *BackupMeta) GetStorageType() StorageType {
	if m != nil {
		return m.StorageType
	}
	return StorageType_LOCAL_DISK
}

func (m *BackupMeta) GetEndTime() *time.Time {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *BackupMeta) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *BackupMeta) GetBackupType() BackupType {
	if m != nil {
		return m.BackupType
	}
	return BackupType_XTRABACKUP_FULL
}

func (m *BackupMeta) GetDb() DatabaseID {
	if m != nil {
		return m.Db
	}
	return nil
}

func (m *BackupMeta) GetKey() Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *BackupMeta) GetBaseTimePoint() TimePoint {
	if m != nil {
		return m.BaseTimePoint
	}
	return nil
}

func (m *BackupMeta) GetXtrabackup() *XtrabackupMeta {
	if x, ok := m.GetDetails().(*BackupMeta_Xtrabackup); ok {
		return x.Xtrabackup
	}
	return nil
}

func (m *BackupMeta) GetMysqldump() *MysqldumpMeta {
	if x, ok := m.GetDetails().(*BackupMeta_Mysqldump); ok {
		return x.Mysqldump
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*BackupMeta) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _BackupMeta_OneofMarshaler, _BackupMeta_OneofUnmarshaler, _BackupMeta_OneofSizer, []interface{}{
		(*BackupMeta_Xtrabackup)(nil),
		(*BackupMeta_Mysqldump)(nil),
	}
}

func _BackupMeta_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*BackupMeta)
	// details
	switch x := m.Details.(type) {
	case *BackupMeta_Xtrabackup:
		_ = b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Xtrabackup); err != nil {
			return err
		}
	case *BackupMeta_Mysqldump:
		_ = b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Mysqldump); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("BackupMeta.Details has unexpected type %T", x)
	}
	return nil
}

func _BackupMeta_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*BackupMeta)
	switch tag {
	case 12: // details.xtrabackup
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(XtrabackupMeta)
		err := b.DecodeMessage(msg)
		m.Details = &BackupMeta_Xtrabackup{msg}
		return true, err
	case 13: // details.mysqldump
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MysqldumpMeta)
		err := b.DecodeMessage(msg)
		m.Details = &BackupMeta_Mysqldump{msg}
		return true, err
	default:
		return false, nil
	}
}

func _BackupMeta_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*BackupMeta)
	// details
	switch x := m.Details.(type) {
	case *BackupMeta_Xtrabackup:
		s := proto.Size(x.Xtrabackup)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BackupMeta_Mysqldump:
		s := proto.Size(x.Mysqldump)
		n += proto.SizeVarint(13<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type XtrabackupMeta struct {
	Checkpoints *XtrabackupCheckpoints `protobuf:"bytes,1,opt,name=checkpoints" json:"checkpoints,omitempty"`
}

func (m *XtrabackupMeta) Reset()                    { *m = XtrabackupMeta{} }
func (m *XtrabackupMeta) String() string            { return proto.CompactTextString(m) }
func (*XtrabackupMeta) ProtoMessage()               {}
func (*XtrabackupMeta) Descriptor() ([]byte, []int) { return fileDescriptorMetadata, []int{3} }

func (m *XtrabackupMeta) GetCheckpoints() *XtrabackupCheckpoints {
	if m != nil {
		return m.Checkpoints
	}
	return nil
}

type MysqldumpMeta struct {
}

func (m *MysqldumpMeta) Reset()                    { *m = MysqldumpMeta{} }
func (m *MysqldumpMeta) String() string            { return proto.CompactTextString(m) }
func (*MysqldumpMeta) ProtoMessage()               {}
func (*MysqldumpMeta) Descriptor() ([]byte, []int) { return fileDescriptorMetadata, []int{4} }

type XtrabackupCheckpoints struct {
	BackupType        string `protobuf:"bytes,1,opt,name=backup_type,json=backupType,proto3" json:"backup_type,omitempty" ini:"backup_type"`
	FromLsn           string `protobuf:"bytes,2,opt,name=from_lsn,json=fromLsn,proto3" json:"from_lsn,omitempty" ini:"from_lsn"`
	ToLsn             string `protobuf:"bytes,3,opt,name=to_lsn,json=toLsn,proto3" json:"to_lsn,omitempty" ini:"to_lsn"`
	LastLsn           string `protobuf:"bytes,4,opt,name=last_lsn,json=lastLsn,proto3" json:"last_lsn,omitempty" ini:"last_lsn"`
	Compact           int32  `protobuf:"varint,5,opt,name=compact,proto3" json:"compact,omitempty" ini:"compact"`
	RecoverBinlogInfo int32  `protobuf:"varint,6,opt,name=recover_binlog_info,json=recoverBinlogInfo,proto3" json:"recover_binlog_info,omitempty" ini:"recover_binlog_info"`
}

func (m *XtrabackupCheckpoints) Reset()                    { *m = XtrabackupCheckpoints{} }
func (m *XtrabackupCheckpoints) String() string            { return proto.CompactTextString(m) }
func (*XtrabackupCheckpoints) ProtoMessage()               {}
func (*XtrabackupCheckpoints) Descriptor() ([]byte, []int) { return fileDescriptorMetadata, []int{5} }

func (m *XtrabackupCheckpoints) GetBackupType() string {
	if m != nil {
		return m.BackupType
	}
	return ""
}

func (m *XtrabackupCheckpoints) GetFromLsn() string {
	if m != nil {
		return m.FromLsn
	}
	return ""
}

func (m *XtrabackupCheckpoints) GetToLsn() string {
	if m != nil {
		return m.ToLsn
	}
	return ""
}

func (m *XtrabackupCheckpoints) GetLastLsn() string {
	if m != nil {
		return m.LastLsn
	}
	return ""
}

func (m *XtrabackupCheckpoints) GetCompact() int32 {
	if m != nil {
		return m.Compact
	}
	return 0
}

func (m *XtrabackupCheckpoints) GetRecoverBinlogInfo() int32 {
	if m != nil {
		return m.RecoverBinlogInfo
	}
	return 0
}

func init() {
	proto.RegisterType((*DiskMeta)(nil), "polypb.DiskMeta")
	proto.RegisterType((*NodeMeta)(nil), "polypb.NodeMeta")
	proto.RegisterType((*BackupMeta)(nil), "polypb.BackupMeta")
	proto.RegisterType((*XtrabackupMeta)(nil), "polypb.XtrabackupMeta")
	proto.RegisterType((*MysqldumpMeta)(nil), "polypb.MysqldumpMeta")
	proto.RegisterType((*XtrabackupCheckpoints)(nil), "polypb.XtrabackupCheckpoints")
	proto.RegisterEnum("polypb.StorageType", StorageType_name, StorageType_value)
	proto.RegisterEnum("polypb.BackupType", BackupType_name, BackupType_value)
}
func (m *DiskMeta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DiskMeta) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Total != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(m.Total))
	}
	if m.Avail != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(m.Avail))
	}
	return i, nil
}

func (m *NodeMeta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeMeta) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Disk != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(m.Disk.Size()))
		n1, err := m.Disk.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.Addr) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.Addr)))
		i += copy(dAtA[i:], m.Addr)
	}
	if len(m.StoreDir) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.StoreDir)))
		i += copy(dAtA[i:], m.StoreDir)
	}
	if len(m.NodeId) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.NodeId)))
		i += copy(dAtA[i:], m.NodeId)
	}
	return i, nil
}

func (m *BackupMeta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BackupMeta) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.StoredTime != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdTime(*m.StoredTime)))
		n2, err := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.StoredTime, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if len(m.NodeId) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.NodeId)))
		i += copy(dAtA[i:], m.NodeId)
	}
	if len(m.Host) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.Host)))
		i += copy(dAtA[i:], m.Host)
	}
	if m.StorageType != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(m.StorageType))
	}
	if m.EndTime != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdTime(*m.EndTime)))
		n3, err := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.EndTime, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.FileSize != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(m.FileSize))
	}
	if m.BackupType != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(m.BackupType))
	}
	if len(m.Db) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.Db)))
		i += copy(dAtA[i:], m.Db)
	}
	if len(m.Key) > 0 {
		dAtA[i] = 0x52
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.Key)))
		i += copy(dAtA[i:], m.Key)
	}
	if len(m.BaseTimePoint) > 0 {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.BaseTimePoint)))
		i += copy(dAtA[i:], m.BaseTimePoint)
	}
	if m.Details != nil {
		nn4, err := m.Details.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += nn4
	}
	return i, nil
}

func (m *BackupMeta_Xtrabackup) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.Xtrabackup != nil {
		dAtA[i] = 0x62
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(m.Xtrabackup.Size()))
		n5, err := m.Xtrabackup.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	return i, nil
}
func (m *BackupMeta_Mysqldump) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.Mysqldump != nil {
		dAtA[i] = 0x6a
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(m.Mysqldump.Size()))
		n6, err := m.Mysqldump.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	return i, nil
}
func (m *XtrabackupMeta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *XtrabackupMeta) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Checkpoints != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(m.Checkpoints.Size()))
		n7, err := m.Checkpoints.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n7
	}
	return i, nil
}

func (m *MysqldumpMeta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MysqldumpMeta) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *XtrabackupCheckpoints) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *XtrabackupCheckpoints) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.BackupType) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.BackupType)))
		i += copy(dAtA[i:], m.BackupType)
	}
	if len(m.FromLsn) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.FromLsn)))
		i += copy(dAtA[i:], m.FromLsn)
	}
	if len(m.ToLsn) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.ToLsn)))
		i += copy(dAtA[i:], m.ToLsn)
	}
	if len(m.LastLsn) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.LastLsn)))
		i += copy(dAtA[i:], m.LastLsn)
	}
	if m.Compact != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(m.Compact))
	}
	if m.RecoverBinlogInfo != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintMetadata(dAtA, i, uint64(m.RecoverBinlogInfo))
	}
	return i, nil
}

func encodeVarintMetadata(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *DiskMeta) Size() (n int) {
	var l int
	_ = l
	if m.Total != 0 {
		n += 1 + sovMetadata(uint64(m.Total))
	}
	if m.Avail != 0 {
		n += 1 + sovMetadata(uint64(m.Avail))
	}
	return n
}

func (m *NodeMeta) Size() (n int) {
	var l int
	_ = l
	if m.Disk != nil {
		l = m.Disk.Size()
		n += 1 + l + sovMetadata(uint64(l))
	}
	l = len(m.Addr)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	l = len(m.StoreDir)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	l = len(m.NodeId)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	return n
}

func (m *BackupMeta) Size() (n int) {
	var l int
	_ = l
	if m.StoredTime != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.StoredTime)
		n += 1 + l + sovMetadata(uint64(l))
	}
	l = len(m.NodeId)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	l = len(m.Host)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	if m.StorageType != 0 {
		n += 1 + sovMetadata(uint64(m.StorageType))
	}
	if m.EndTime != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.EndTime)
		n += 1 + l + sovMetadata(uint64(l))
	}
	if m.FileSize != 0 {
		n += 1 + sovMetadata(uint64(m.FileSize))
	}
	if m.BackupType != 0 {
		n += 1 + sovMetadata(uint64(m.BackupType))
	}
	l = len(m.Db)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	l = len(m.BaseTimePoint)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	if m.Details != nil {
		n += m.Details.Size()
	}
	return n
}

func (m *BackupMeta_Xtrabackup) Size() (n int) {
	var l int
	_ = l
	if m.Xtrabackup != nil {
		l = m.Xtrabackup.Size()
		n += 1 + l + sovMetadata(uint64(l))
	}
	return n
}
func (m *BackupMeta_Mysqldump) Size() (n int) {
	var l int
	_ = l
	if m.Mysqldump != nil {
		l = m.Mysqldump.Size()
		n += 1 + l + sovMetadata(uint64(l))
	}
	return n
}
func (m *XtrabackupMeta) Size() (n int) {
	var l int
	_ = l
	if m.Checkpoints != nil {
		l = m.Checkpoints.Size()
		n += 1 + l + sovMetadata(uint64(l))
	}
	return n
}

func (m *MysqldumpMeta) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *XtrabackupCheckpoints) Size() (n int) {
	var l int
	_ = l
	l = len(m.BackupType)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	l = len(m.FromLsn)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	l = len(m.ToLsn)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	l = len(m.LastLsn)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	if m.Compact != 0 {
		n += 1 + sovMetadata(uint64(m.Compact))
	}
	if m.RecoverBinlogInfo != 0 {
		n += 1 + sovMetadata(uint64(m.RecoverBinlogInfo))
	}
	return n
}

func sovMetadata(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMetadata(x uint64) (n int) {
	return sovMetadata(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DiskMeta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetadata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DiskMeta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DiskMeta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Avail", wireType)
			}
			m.Avail = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Avail |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMetadata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetadata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeMeta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetadata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeMeta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeMeta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Disk", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Disk == nil {
				m.Disk = &DiskMeta{}
			}
			if err := m.Disk.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreDir", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoreDir = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeId = append(m.NodeId[:0], dAtA[iNdEx:postIndex]...)
			if m.NodeId == nil {
				m.NodeId = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetadata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetadata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BackupMeta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetadata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BackupMeta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BackupMeta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoredTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StoredTime == nil {
				m.StoredTime = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.StoredTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeId = append(m.NodeId[:0], dAtA[iNdEx:postIndex]...)
			if m.NodeId == nil {
				m.NodeId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Host", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Host = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageType", wireType)
			}
			m.StorageType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StorageType |= (StorageType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EndTime == nil {
				m.EndTime = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileSize", wireType)
			}
			m.FileSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FileSize |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BackupType", wireType)
			}
			m.BackupType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BackupType |= (BackupType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Db", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Db = append(m.Db[:0], dAtA[iNdEx:postIndex]...)
			if m.Db == nil {
				m.Db = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = append(m.Key[:0], dAtA[iNdEx:postIndex]...)
			if m.Key == nil {
				m.Key = []byte{}
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseTimePoint", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseTimePoint = append(m.BaseTimePoint[:0], dAtA[iNdEx:postIndex]...)
			if m.BaseTimePoint == nil {
				m.BaseTimePoint = []byte{}
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Xtrabackup", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &XtrabackupMeta{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Details = &BackupMeta_Xtrabackup{v}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mysqldump", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &MysqldumpMeta{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Details = &BackupMeta_Mysqldump{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetadata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetadata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *XtrabackupMeta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetadata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: XtrabackupMeta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: XtrabackupMeta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Checkpoints", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Checkpoints == nil {
				m.Checkpoints = &XtrabackupCheckpoints{}
			}
			if err := m.Checkpoints.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetadata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetadata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MysqldumpMeta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetadata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MysqldumpMeta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MysqldumpMeta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMetadata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetadata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *XtrabackupCheckpoints) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetadata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: XtrabackupCheckpoints: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: XtrabackupCheckpoints: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BackupType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BackupType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromLsn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromLsn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToLsn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToLsn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastLsn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastLsn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Compact", wireType)
			}
			m.Compact = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Compact |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecoverBinlogInfo", wireType)
			}
			m.RecoverBinlogInfo = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecoverBinlogInfo |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMetadata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetadata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMetadata(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMetadata
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMetadata
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMetadata
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMetadata(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMetadata = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMetadata   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("polypb/metadata.proto", fileDescriptorMetadata) }

var fileDescriptorMetadata = []byte{
	// 818 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0xaf, 0xd3, 0x34, 0x7f, 0x5e, 0x9a, 0x34, 0x9d, 0x52, 0xe4, 0xed, 0x6a, 0xe3, 0xca, 0x20,
	0x51, 0x2d, 0x34, 0x95, 0x76, 0xb5, 0x15, 0x82, 0x03, 0xaa, 0x1b, 0x10, 0x51, 0x93, 0xa5, 0xeb,
	0xb6, 0xd2, 0x72, 0xb2, 0xc6, 0xf1, 0x24, 0x1d, 0xc5, 0xf6, 0x18, 0x7b, 0xba, 0x22, 0xfb, 0x01,
	0x38, 0x73, 0xe4, 0xcb, 0x70, 0xe7, 0x88, 0xf8, 0x00, 0x06, 0x95, 0x6f, 0x90, 0x63, 0x4f, 0x68,
	0xde, 0xc4, 0x6d, 0x02, 0x8b, 0xb4, 0xb7, 0xf7, 0x7e, 0xef, 0xf7, 0x7b, 0xef, 0x37, 0xcf, 0x33,
	0x86, 0xdd, 0x44, 0x84, 0xb3, 0xc4, 0x3f, 0x8a, 0x98, 0xa4, 0x01, 0x95, 0xb4, 0x9b, 0xa4, 0x42,
	0x0a, 0x52, 0xd1, 0xf0, 0x9e, 0x35, 0x11, 0x62, 0x12, 0xb2, 0x23, 0x44, 0xfd, 0x9b, 0xf1, 0x91,
	0xe4, 0x11, 0xcb, 0x24, 0x8d, 0x12, 0x4d, 0xdc, 0x3b, 0x9c, 0x70, 0x79, 0x7d, 0xe3, 0x77, 0x47,
	0x22, 0x3a, 0x9a, 0x88, 0x89, 0x78, 0x60, 0xaa, 0x0c, 0x13, 0x8c, 0x34, 0xdd, 0x3e, 0x86, 0x5a,
	0x8f, 0x67, 0xd3, 0x21, 0x93, 0x94, 0x7c, 0x00, 0x1b, 0x52, 0x48, 0x1a, 0x9a, 0xc6, 0xbe, 0x71,
	0x50, 0x76, 0x75, 0xa2, 0x50, 0xfa, 0x86, 0xf2, 0xd0, 0x2c, 0x69, 0x14, 0x13, 0xfb, 0x27, 0x03,
	0x6a, 0x2f, 0x45, 0xc0, 0x50, 0xf8, 0x31, 0x94, 0x03, 0x9e, 0x4d, 0x51, 0xd7, 0x78, 0xd6, 0xee,
	0x6a, 0xaf, 0xdd, 0xa2, 0xb1, 0x8b, 0x55, 0x42, 0xa0, 0x4c, 0x83, 0x20, 0xc5, 0x3e, 0x75, 0x17,
	0x63, 0xf2, 0x18, 0xea, 0x99, 0x14, 0x29, 0xf3, 0x02, 0x9e, 0x9a, 0xeb, 0x58, 0xa8, 0x21, 0xd0,
	0xe3, 0x29, 0xf9, 0x08, 0xaa, 0xb1, 0x08, 0x98, 0xc7, 0x03, 0xb3, 0xbc, 0x6f, 0x1c, 0x6c, 0x3a,
	0x70, 0x97, 0x5b, 0x15, 0x35, 0xb5, 0xdf, 0x73, 0x2b, 0xaa, 0xd4, 0x0f, 0xec, 0x5f, 0xcb, 0x00,
	0x0e, 0x1d, 0x4d, 0x6f, 0x12, 0xb4, 0x72, 0x02, 0x0d, 0xd4, 0x07, 0x9e, 0x5a, 0xcc, 0xc2, 0xd1,
	0x5e, 0x57, 0x6f, 0xad, 0x5b, 0xec, 0xa2, 0x7b, 0x59, 0x6c, 0xcd, 0x29, 0xff, 0xfc, 0xa7, 0x65,
	0xb8, 0xa0, 0x45, 0x0a, 0x5e, 0x1e, 0x5b, 0xfa, 0xbf, 0xb1, 0xea, 0x30, 0xd7, 0x22, 0x93, 0x0b,
	0xcf, 0x18, 0x93, 0x63, 0xd8, 0x54, 0x6d, 0xe8, 0x84, 0x79, 0x72, 0x96, 0x30, 0x34, 0xdd, 0x7a,
	0xb6, 0x53, 0xac, 0xe3, 0x42, 0xd7, 0x2e, 0x67, 0x09, 0x73, 0x1b, 0xd9, 0x43, 0x42, 0xbe, 0x84,
	0x1a, 0x8b, 0x17, 0x86, 0x37, 0xde, 0xd3, 0x70, 0x95, 0xc5, 0xda, 0xed, 0x63, 0xa8, 0x8f, 0x79,
	0xc8, 0xbc, 0x8c, 0xbf, 0x65, 0x66, 0x65, 0xdf, 0x38, 0x58, 0x77, 0x6b, 0x0a, 0xb8, 0xe0, 0x6f,
	0x19, 0x79, 0x0e, 0x0d, 0x1f, 0x77, 0xa3, 0x0d, 0x55, 0xd1, 0x10, 0x29, 0x0c, 0xe9, 0xb5, 0xa1,
	0x1f, 0xf0, 0xef, 0x63, 0xd2, 0x81, 0x52, 0xe0, 0x9b, 0x35, 0x3c, 0x7a, 0xeb, 0x2e, 0xb7, 0xa0,
	0x47, 0x25, 0xf5, 0x69, 0xa6, 0x8e, 0x5f, 0x0a, 0x7c, 0xf2, 0x08, 0xd6, 0xa7, 0x6c, 0x66, 0x02,
	0x12, 0xaa, 0x77, 0xb9, 0xb5, 0x7e, 0xc6, 0x66, 0xae, 0xc2, 0xc8, 0x0b, 0xd8, 0x52, 0x44, 0x3c,
	0x8a, 0x97, 0x08, 0x1e, 0x4b, 0xb3, 0x81, 0xb4, 0xe6, 0x5d, 0x6e, 0xd5, 0x95, 0xdf, 0x73, 0x05,
	0xba, 0x4d, 0xc5, 0xba, 0x4f, 0xc9, 0xe7, 0x00, 0x3f, 0xca, 0x94, 0x6a, 0x0f, 0xe6, 0x26, 0xae,
	0xe0, 0xc3, 0xc2, 0xe5, 0xeb, 0xfb, 0x8a, 0xfa, 0xc0, 0xdf, 0xae, 0xb9, 0x4b, 0x5c, 0xf2, 0x02,
	0xea, 0xd1, 0x2c, 0xfb, 0x21, 0x0c, 0x6e, 0xa2, 0xc4, 0x6c, 0xa2, 0x70, 0xb7, 0x10, 0x0e, 0x8b,
	0xc2, 0x42, 0xf7, 0xc0, 0x74, 0xea, 0x50, 0x0d, 0x98, 0xa4, 0x3c, 0xcc, 0xec, 0x57, 0xd0, 0x5a,
	0x9d, 0x40, 0xbe, 0x82, 0xc6, 0xe8, 0x9a, 0x8d, 0xa6, 0xe8, 0x3f, 0x5b, 0x5c, 0xa1, 0x27, 0xff,
	0xb5, 0x73, 0xfa, 0x40, 0x72, 0x97, 0x15, 0xf6, 0x16, 0x34, 0x57, 0x66, 0xdb, 0x7f, 0x94, 0x60,
	0xf7, 0x9d, 0x3a, 0x72, 0xbc, 0xfa, 0x81, 0xd4, 0xac, 0xba, 0xb3, 0x3b, 0xcf, 0xad, 0x6d, 0x1e,
	0xf3, 0x2f, 0xec, 0xa5, 0x9a, 0xbd, 0xf2, 0x8d, 0x0e, 0xa1, 0x36, 0x4e, 0x45, 0xe4, 0x85, 0x59,
	0xac, 0xdf, 0x93, 0x43, 0xe6, 0xb9, 0xd5, 0x42, 0x51, 0x51, 0xb0, 0xdd, 0xaa, 0x0a, 0x07, 0x59,
	0x4c, 0x3e, 0x81, 0x8a, 0x14, 0x48, 0xc6, 0xfb, 0xea, 0xb4, 0xe7, 0xb9, 0xb5, 0x89, 0x64, 0x0d,
	0xdb, 0xea, 0xb1, 0x2b, 0xe2, 0x21, 0xd4, 0x42, 0x9a, 0x49, 0xa4, 0x96, 0xff, 0xd5, 0xb7, 0x28,
	0xd8, 0x6e, 0x55, 0x85, 0x8a, 0xfe, 0x29, 0x54, 0x47, 0x22, 0x4a, 0xe8, 0x48, 0xe2, 0xc5, 0xdd,
	0x70, 0xb6, 0xe7, 0xb9, 0xd5, 0x44, 0xf6, 0x02, 0xb7, 0xdd, 0x82, 0x41, 0x86, 0xb0, 0x93, 0xb2,
	0x91, 0x78, 0xc3, 0x52, 0xcf, 0xe7, 0x71, 0x28, 0x26, 0x1e, 0x8f, 0xc7, 0x02, 0xef, 0xec, 0x86,
	0xf3, 0x64, 0x9e, 0x5b, 0x8f, 0x50, 0xf8, 0x0e, 0x8e, 0xed, 0x6e, 0x2f, 0x50, 0x07, 0xc1, 0x7e,
	0x3c, 0x16, 0x4f, 0x3f, 0x83, 0xc6, 0xd2, 0x8b, 0x22, 0x2d, 0x80, 0xc1, 0x77, 0xa7, 0x27, 0x03,
	0xaf, 0xd7, 0xbf, 0x38, 0x6b, 0xaf, 0x91, 0x26, 0xd4, 0x75, 0x3e, 0xfc, 0x7a, 0xd8, 0x36, 0x9e,
	0xf6, 0x8a, 0xbf, 0x04, 0x92, 0x77, 0x60, 0xeb, 0xf5, 0xa5, 0x7b, 0xe2, 0x9c, 0x9c, 0x9e, 0x5d,
	0x9d, 0x7b, 0xdf, 0x5c, 0x0d, 0x06, 0xed, 0x35, 0x42, 0xa0, 0xb5, 0x04, 0xf6, 0x5f, 0x9e, 0xb6,
	0x0d, 0xd5, 0x65, 0xf8, 0xfd, 0xc5, 0xab, 0x41, 0xef, 0x6a, 0x78, 0xde, 0x2e, 0x39, 0xed, 0xdf,
	0x6e, 0x3b, 0xc6, 0xef, 0xb7, 0x1d, 0xe3, 0xaf, 0xdb, 0x8e, 0xf1, 0xcb, 0xdf, 0x9d, 0x35, 0xbf,
	0x82, 0x2f, 0xf4, 0xf9, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x36, 0x47, 0x99, 0x35, 0xb7, 0x05,
	0x00, 0x00,
}
