// Code generated by protoc-gen-go. DO NOT EDIT.
// source: polypb/metadata.proto

/*
Package polypb is a generated protocol buffer package.

It is generated from these files:
	polypb/metadata.proto

It has these top-level messages:
	DiskInfo
	NodeInfo
	NodeInfoMap
	BackupInfo
	BackupMetadata
	BackupInfoWithKey
	BackupInfoMap
*/
package polypb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StoredType int32

const (
	StoredType_LOCAL StoredType = 0
)

var StoredType_name = map[int32]string{
	0: "LOCAL",
}
var StoredType_value = map[string]int32{
	"LOCAL": 0,
}

func (x StoredType) String() string {
	return proto.EnumName(StoredType_name, int32(x))
}
func (StoredType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type BackupType int32

const (
	BackupType_FULL BackupType = 0
	BackupType_INC  BackupType = 1
)

var BackupType_name = map[int32]string{
	0: "FULL",
	1: "INC",
}
var BackupType_value = map[string]int32{
	"FULL": 0,
	"INC":  1,
}

func (x BackupType) String() string {
	return proto.EnumName(BackupType_name, int32(x))
}
func (BackupType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type DiskInfo struct {
	Total uint64 `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
	Avail uint64 `protobuf:"varint,2,opt,name=avail" json:"avail,omitempty"`
}

func (m *DiskInfo) Reset()                    { *m = DiskInfo{} }
func (m *DiskInfo) String() string            { return proto.CompactTextString(m) }
func (*DiskInfo) ProtoMessage()               {}
func (*DiskInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DiskInfo) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *DiskInfo) GetAvail() uint64 {
	if m != nil {
		return m.Avail
	}
	return 0
}

type NodeInfo struct {
	DiskInfo *DiskInfo `protobuf:"bytes,1,opt,name=diskInfo" json:"diskInfo,omitempty"`
	Addr     string    `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
	StoreDir string    `protobuf:"bytes,3,opt,name=store_dir,json=storeDir" json:"store_dir,omitempty"`
}

func (m *NodeInfo) Reset()                    { *m = NodeInfo{} }
func (m *NodeInfo) String() string            { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()               {}
func (*NodeInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NodeInfo) GetDiskInfo() *DiskInfo {
	if m != nil {
		return m.DiskInfo
	}
	return nil
}

func (m *NodeInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *NodeInfo) GetStoreDir() string {
	if m != nil {
		return m.StoreDir
	}
	return ""
}

type NodeInfoMap struct {
	Nodes map[string]*NodeInfo `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *NodeInfoMap) Reset()                    { *m = NodeInfoMap{} }
func (m *NodeInfoMap) String() string            { return proto.CompactTextString(m) }
func (*NodeInfoMap) ProtoMessage()               {}
func (*NodeInfoMap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NodeInfoMap) GetNodes() map[string]*NodeInfo {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type BackupInfo struct {
	FullBackup *BackupMetadata   `protobuf:"bytes,1,opt,name=full_backup,json=fullBackup" json:"full_backup,omitempty"`
	IncBackups []*BackupMetadata `protobuf:"bytes,2,rep,name=inc_backups,json=incBackups" json:"inc_backups,omitempty"`
	Db         string            `protobuf:"bytes,3,opt,name=db" json:"db,omitempty"`
}

func (m *BackupInfo) Reset()                    { *m = BackupInfo{} }
func (m *BackupInfo) String() string            { return proto.CompactTextString(m) }
func (*BackupInfo) ProtoMessage()               {}
func (*BackupInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BackupInfo) GetFullBackup() *BackupMetadata {
	if m != nil {
		return m.FullBackup
	}
	return nil
}

func (m *BackupInfo) GetIncBackups() []*BackupMetadata {
	if m != nil {
		return m.IncBackups
	}
	return nil
}

func (m *BackupInfo) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

type BackupMetadata struct {
	StoredTime *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=stored_time,json=storedTime" json:"stored_time,omitempty"`
	NodeName   string                     `protobuf:"bytes,2,opt,name=node_name,json=nodeName" json:"node_name,omitempty"`
	Host       string                     `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
	StoredType StoredType                 `protobuf:"varint,4,opt,name=stored_type,json=storedType,enum=polypb.StoredType" json:"stored_type,omitempty"`
	EndTime    *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	FileSize   uint64                     `protobuf:"varint,6,opt,name=file_size,json=fileSize" json:"file_size,omitempty"`
	BackupType BackupType                 `protobuf:"varint,7,opt,name=backup_type,json=backupType,enum=polypb.BackupType" json:"backup_type,omitempty"`
	Db         string                     `protobuf:"bytes,8,opt,name=db" json:"db,omitempty"`
	ToLsn      string                     `protobuf:"bytes,9,opt,name=to_lsn,json=toLsn" json:"to_lsn,omitempty"`
	Key        string                     `protobuf:"bytes,10,opt,name=key" json:"key,omitempty"`
}

func (m *BackupMetadata) Reset()                    { *m = BackupMetadata{} }
func (m *BackupMetadata) String() string            { return proto.CompactTextString(m) }
func (*BackupMetadata) ProtoMessage()               {}
func (*BackupMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BackupMetadata) GetStoredTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.StoredTime
	}
	return nil
}

func (m *BackupMetadata) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *BackupMetadata) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *BackupMetadata) GetStoredType() StoredType {
	if m != nil {
		return m.StoredType
	}
	return StoredType_LOCAL
}

func (m *BackupMetadata) GetEndTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *BackupMetadata) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *BackupMetadata) GetBackupType() BackupType {
	if m != nil {
		return m.BackupType
	}
	return BackupType_FULL
}

func (m *BackupMetadata) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *BackupMetadata) GetToLsn() string {
	if m != nil {
		return m.ToLsn
	}
	return ""
}

func (m *BackupMetadata) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type BackupInfoWithKey struct {
	Key  string      `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Info *BackupInfo `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *BackupInfoWithKey) Reset()                    { *m = BackupInfoWithKey{} }
func (m *BackupInfoWithKey) String() string            { return proto.CompactTextString(m) }
func (*BackupInfoWithKey) ProtoMessage()               {}
func (*BackupInfoWithKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BackupInfoWithKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *BackupInfoWithKey) GetInfo() *BackupInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type BackupInfoMap struct {
	DbToBackups map[string]*BackupInfo `protobuf:"bytes,1,rep,name=db_to_backups,json=dbToBackups" json:"db_to_backups,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *BackupInfoMap) Reset()                    { *m = BackupInfoMap{} }
func (m *BackupInfoMap) String() string            { return proto.CompactTextString(m) }
func (*BackupInfoMap) ProtoMessage()               {}
func (*BackupInfoMap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BackupInfoMap) GetDbToBackups() map[string]*BackupInfo {
	if m != nil {
		return m.DbToBackups
	}
	return nil
}

func init() {
	proto.RegisterType((*DiskInfo)(nil), "polypb.DiskInfo")
	proto.RegisterType((*NodeInfo)(nil), "polypb.NodeInfo")
	proto.RegisterType((*NodeInfoMap)(nil), "polypb.NodeInfoMap")
	proto.RegisterType((*BackupInfo)(nil), "polypb.BackupInfo")
	proto.RegisterType((*BackupMetadata)(nil), "polypb.BackupMetadata")
	proto.RegisterType((*BackupInfoWithKey)(nil), "polypb.BackupInfoWithKey")
	proto.RegisterType((*BackupInfoMap)(nil), "polypb.BackupInfoMap")
	proto.RegisterEnum("polypb.StoredType", StoredType_name, StoredType_value)
	proto.RegisterEnum("polypb.BackupType", BackupType_name, BackupType_value)
}

func init() { proto.RegisterFile("polypb/metadata.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 600 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x5d, 0xd2, 0xa6, 0x4b, 0x6f, 0xb4, 0x29, 0x58, 0x0c, 0xa2, 0x22, 0xb1, 0x29, 0x0f, 0x53,
	0x35, 0xa1, 0x4c, 0xda, 0xf8, 0x12, 0x3c, 0xc1, 0x0a, 0xd2, 0x46, 0x5b, 0xa4, 0x6c, 0x88, 0xc7,
	0xc8, 0xa9, 0xdd, 0xcd, 0x6a, 0x1a, 0x47, 0x89, 0x3b, 0x29, 0xfb, 0x11, 0xf0, 0x53, 0xf8, 0x75,
	0xbc, 0x23, 0xdb, 0xf9, 0x58, 0x47, 0x11, 0x6f, 0xd7, 0xc7, 0xe7, 0xde, 0x7b, 0x7c, 0xef, 0x31,
	0xec, 0x65, 0x3c, 0x29, 0xb3, 0xf8, 0x78, 0x49, 0x05, 0x26, 0x58, 0xe0, 0x20, 0xcb, 0xb9, 0xe0,
	0xa8, 0xa7, 0xe1, 0xc1, 0xfe, 0x35, 0xe7, 0xd7, 0x09, 0x3d, 0x56, 0x68, 0xbc, 0x9a, 0x1f, 0x0b,
	0xb6, 0xa4, 0x85, 0xc0, 0xcb, 0x4c, 0x13, 0xfd, 0xd7, 0x60, 0x8f, 0x58, 0xb1, 0x38, 0x4f, 0xe7,
	0x1c, 0x3d, 0x06, 0x4b, 0x70, 0x81, 0x13, 0xcf, 0x38, 0x30, 0x86, 0xdd, 0x50, 0x1f, 0x24, 0x8a,
	0x6f, 0x31, 0x4b, 0x3c, 0x53, 0xa3, 0xea, 0xe0, 0x33, 0xb0, 0xa7, 0x9c, 0x50, 0x95, 0xf7, 0x02,
	0x6c, 0x52, 0xd5, 0x50, 0xa9, 0xce, 0x89, 0x1b, 0xe8, 0xfe, 0x41, 0x5d, 0x3b, 0x6c, 0x18, 0x08,
	0x41, 0x17, 0x13, 0x92, 0xab, 0x72, 0xfd, 0x50, 0xc5, 0xe8, 0x19, 0xf4, 0x0b, 0xc1, 0x73, 0x1a,
	0x11, 0x96, 0x7b, 0x1d, 0x75, 0x61, 0x2b, 0x60, 0xc4, 0x72, 0xff, 0xa7, 0x01, 0x4e, 0xdd, 0x6b,
	0x82, 0x33, 0xf4, 0x12, 0xac, 0x94, 0x13, 0x5a, 0x78, 0xc6, 0x41, 0x67, 0xe8, 0x9c, 0x3c, 0xaf,
	0x7b, 0xdd, 0xe3, 0xa8, 0xb8, 0xf8, 0x94, 0x8a, 0xbc, 0x0c, 0x35, 0x79, 0x70, 0x01, 0xd0, 0x82,
	0xc8, 0x85, 0xce, 0x82, 0x96, 0x4a, 0x6d, 0x3f, 0x94, 0x21, 0x3a, 0x04, 0xeb, 0x16, 0x27, 0x2b,
	0xaa, 0x74, 0xdd, 0x7b, 0x41, 0x5d, 0x35, 0xd4, 0xd7, 0xef, 0xcc, 0xb7, 0x86, 0xff, 0xc3, 0x00,
	0xf8, 0x88, 0x67, 0x8b, 0x55, 0xa6, 0x5e, 0xf4, 0x06, 0x9c, 0xf9, 0x2a, 0x49, 0xa2, 0x58, 0x41,
	0xd5, 0x08, 0x9e, 0xd4, 0x05, 0x34, 0x71, 0x52, 0xed, 0x27, 0x04, 0x49, 0xd5, 0x98, 0x4c, 0x64,
	0xe9, 0xac, 0xca, 0x2b, 0x3c, 0x53, 0xbd, 0xe7, 0x9f, 0x89, 0x2c, 0x9d, 0x69, 0xa8, 0x40, 0xbb,
	0x60, 0x92, 0xb8, 0x1a, 0x94, 0x49, 0x62, 0xff, 0xb7, 0x09, 0xbb, 0xeb, 0x74, 0xf4, 0x1e, 0x1c,
	0x35, 0x41, 0x12, 0xc9, 0x95, 0x57, 0xa2, 0x06, 0x81, 0xf6, 0x43, 0x50, 0xfb, 0x21, 0xb8, 0xaa,
	0xfd, 0x10, 0x82, 0xa6, 0x4b, 0x40, 0xee, 0x43, 0x4e, 0x2d, 0x4a, 0xf1, 0x92, 0x56, 0x8b, 0xb2,
	0x25, 0x30, 0xc5, 0x4b, 0x2a, 0x17, 0x78, 0xc3, 0x0b, 0x51, 0xb5, 0x57, 0x31, 0x3a, 0x6d, 0xbb,
	0x95, 0x19, 0xf5, 0xba, 0x07, 0xc6, 0x70, 0xf7, 0x04, 0xd5, 0x2f, 0xb9, 0xd4, 0x95, 0xcb, 0x8c,
	0x36, 0x5d, 0xca, 0x8c, 0xa2, 0x57, 0x60, 0xd3, 0xb4, 0xd2, 0x67, 0xfd, 0x57, 0xdf, 0x36, 0x4d,
	0x1b, 0x71, 0x73, 0x96, 0xd0, 0xa8, 0x60, 0x77, 0xd4, 0xeb, 0x29, 0x53, 0xda, 0x12, 0xb8, 0x64,
	0x77, 0x54, 0x0a, 0xd1, 0xe3, 0xd4, 0x42, 0xb6, 0xd7, 0x85, 0xe8, 0x19, 0x69, 0x21, 0x71, 0x13,
	0x57, 0xe3, 0xb4, 0xeb, 0x71, 0xa2, 0x3d, 0xe8, 0x09, 0x1e, 0x25, 0x45, 0xea, 0xf5, 0x15, 0x66,
	0x09, 0x3e, 0x2e, 0xd2, 0xda, 0x34, 0xd0, 0x98, 0xc6, 0x9f, 0xc0, 0xa3, 0xd6, 0x07, 0xdf, 0x99,
	0xb8, 0xf9, 0x42, 0x37, 0x7b, 0xab, 0xcb, 0xe4, 0xe7, 0xd0, 0xd6, 0x7a, 0xa0, 0x46, 0x99, 0x4b,
	0xdd, 0xfb, 0xbf, 0x0c, 0xd8, 0x69, 0x41, 0xe9, 0xf5, 0x0b, 0xd8, 0x21, 0x71, 0x24, 0x78, 0xe3,
	0x11, 0xed, 0xf9, 0xc3, 0xbf, 0x4b, 0x48, 0xd7, 0x8f, 0xe2, 0x2b, 0x5e, 0x59, 0x44, 0x7b, 0xdf,
	0x21, 0x2d, 0x32, 0x08, 0xc1, 0x7d, 0x48, 0xd8, 0xa0, 0x75, 0xb8, 0xfe, 0x0f, 0x36, 0x89, 0x6d,
	0x7f, 0xc2, 0xd1, 0x53, 0x80, 0x76, 0xb9, 0xa8, 0x0f, 0xd6, 0xf8, 0xeb, 0xd9, 0x87, 0xb1, 0xbb,
	0x75, 0xb4, 0x5f, 0xff, 0x10, 0x75, 0x61, 0x43, 0xf7, 0xf3, 0xb7, 0xf1, 0xd8, 0xdd, 0x42, 0xdb,
	0xd0, 0x39, 0x9f, 0x9e, 0xb9, 0x46, 0xdc, 0x53, 0x2b, 0x3e, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff,
	0x89, 0x89, 0xe8, 0x0a, 0xc1, 0x04, 0x00, 0x00,
}
