// Automatically generated by MockGen. DO NOT EDIT!
// Source: pkg/storage/storage.go

package storage

import (
	io "io"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// Mock of BackupStorage interface
type MockBackupStorage struct {
	ctrl     *gomock.Controller
	recorder *_MockBackupStorageRecorder
}

// Recorder for MockBackupStorage (not exported)
type _MockBackupStorageRecorder struct {
	mock *MockBackupStorage
}

func NewMockBackupStorage(ctrl *gomock.Controller) *MockBackupStorage {
	mock := &MockBackupStorage{ctrl: ctrl}
	mock.recorder = &_MockBackupStorageRecorder{mock}
	return mock
}

func (_m *MockBackupStorage) EXPECT() *_MockBackupStorageRecorder {
	return _m.recorder
}

func (_m *MockBackupStorage) GetStorageType() string {
	ret := _m.ctrl.Call(_m, "GetStorageType")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockBackupStorageRecorder) GetStorageType() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetStorageType")
}

func (_m *MockBackupStorage) GetLatestToLSN(db string) (string, error) {
	ret := _m.ctrl.Call(_m, "GetLatestToLSN", db)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockBackupStorageRecorder) GetLatestToLSN(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetLatestToLSN", arg0)
}

func (_m *MockBackupStorage) SearchStaringPointByLSN(db string, lsn string) (string, error) {
	ret := _m.ctrl.Call(_m, "SearchStaringPointByLSN", db, lsn)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockBackupStorageRecorder) SearchStaringPointByLSN(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SearchStaringPointByLSN", arg0, arg1)
}

func (_m *MockBackupStorage) TransferTempFullBackup(tempDir string, key string) error {
	ret := _m.ctrl.Call(_m, "TransferTempFullBackup", tempDir, key)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockBackupStorageRecorder) TransferTempFullBackup(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "TransferTempFullBackup", arg0, arg1)
}

func (_m *MockBackupStorage) TransferTempIncBackup(tempDir string, key string) error {
	ret := _m.ctrl.Call(_m, "TransferTempIncBackup", tempDir, key)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockBackupStorageRecorder) TransferTempIncBackup(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "TransferTempIncBackup", arg0, arg1)
}

func (_m *MockBackupStorage) SearchConsecutiveIncBackups(db string, from time.Time) ([]*BackupFile, error) {
	ret := _m.ctrl.Call(_m, "SearchConsecutiveIncBackups", db, from)
	ret0, _ := ret[0].([]*BackupFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockBackupStorageRecorder) SearchConsecutiveIncBackups(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SearchConsecutiveIncBackups", arg0, arg1)
}

func (_m *MockBackupStorage) GetFileStream(key string) (io.Reader, error) {
	ret := _m.ctrl.Call(_m, "GetFileStream", key)
	ret0, _ := ret[0].(io.Reader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockBackupStorageRecorder) GetFileStream(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetFileStream", arg0)
}
