// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tempbackup/tempbackuppb/backup.proto

/*
Package tempbackuppb is a generated protocol buffer package.

It is generated from these files:
	tempbackup/tempbackuppb/backup.proto

It has these top-level messages:
	FullBackupContentStream
	IncBackupContentStream
	BackupReply
*/
package tempbackuppb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FullBackupContentStream struct {
	Db      string `protobuf:"bytes,1,opt,name=db" json:"db,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *FullBackupContentStream) Reset()                    { *m = FullBackupContentStream{} }
func (m *FullBackupContentStream) String() string            { return proto.CompactTextString(m) }
func (*FullBackupContentStream) ProtoMessage()               {}
func (*FullBackupContentStream) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FullBackupContentStream) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *FullBackupContentStream) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type IncBackupContentStream struct {
	Db      string `protobuf:"bytes,1,opt,name=db" json:"db,omitempty"`
	Lsn     string `protobuf:"bytes,2,opt,name=lsn" json:"lsn,omitempty"`
	Content []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *IncBackupContentStream) Reset()                    { *m = IncBackupContentStream{} }
func (m *IncBackupContentStream) String() string            { return proto.CompactTextString(m) }
func (*IncBackupContentStream) ProtoMessage()               {}
func (*IncBackupContentStream) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IncBackupContentStream) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *IncBackupContentStream) GetLsn() string {
	if m != nil {
		return m.Lsn
	}
	return ""
}

func (m *IncBackupContentStream) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type BackupReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *BackupReply) Reset()                    { *m = BackupReply{} }
func (m *BackupReply) String() string            { return proto.CompactTextString(m) }
func (*BackupReply) ProtoMessage()               {}
func (*BackupReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BackupReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*FullBackupContentStream)(nil), "tempbackuppb.FullBackupContentStream")
	proto.RegisterType((*IncBackupContentStream)(nil), "tempbackuppb.IncBackupContentStream")
	proto.RegisterType((*BackupReply)(nil), "tempbackuppb.BackupReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BackupTransferService service

type BackupTransferServiceClient interface {
	TransferFullBackup(ctx context.Context, opts ...grpc.CallOption) (BackupTransferService_TransferFullBackupClient, error)
	TransferIncBackup(ctx context.Context, opts ...grpc.CallOption) (BackupTransferService_TransferIncBackupClient, error)
}

type backupTransferServiceClient struct {
	cc *grpc.ClientConn
}

func NewBackupTransferServiceClient(cc *grpc.ClientConn) BackupTransferServiceClient {
	return &backupTransferServiceClient{cc}
}

func (c *backupTransferServiceClient) TransferFullBackup(ctx context.Context, opts ...grpc.CallOption) (BackupTransferService_TransferFullBackupClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BackupTransferService_serviceDesc.Streams[0], c.cc, "/tempbackuppb.BackupTransferService/TransferFullBackup", opts...)
	if err != nil {
		return nil, err
	}
	x := &backupTransferServiceTransferFullBackupClient{stream}
	return x, nil
}

type BackupTransferService_TransferFullBackupClient interface {
	Send(*FullBackupContentStream) error
	CloseAndRecv() (*BackupReply, error)
	grpc.ClientStream
}

type backupTransferServiceTransferFullBackupClient struct {
	grpc.ClientStream
}

func (x *backupTransferServiceTransferFullBackupClient) Send(m *FullBackupContentStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *backupTransferServiceTransferFullBackupClient) CloseAndRecv() (*BackupReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(BackupReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *backupTransferServiceClient) TransferIncBackup(ctx context.Context, opts ...grpc.CallOption) (BackupTransferService_TransferIncBackupClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BackupTransferService_serviceDesc.Streams[1], c.cc, "/tempbackuppb.BackupTransferService/TransferIncBackup", opts...)
	if err != nil {
		return nil, err
	}
	x := &backupTransferServiceTransferIncBackupClient{stream}
	return x, nil
}

type BackupTransferService_TransferIncBackupClient interface {
	Send(*IncBackupContentStream) error
	CloseAndRecv() (*BackupReply, error)
	grpc.ClientStream
}

type backupTransferServiceTransferIncBackupClient struct {
	grpc.ClientStream
}

func (x *backupTransferServiceTransferIncBackupClient) Send(m *IncBackupContentStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *backupTransferServiceTransferIncBackupClient) CloseAndRecv() (*BackupReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(BackupReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for BackupTransferService service

type BackupTransferServiceServer interface {
	TransferFullBackup(BackupTransferService_TransferFullBackupServer) error
	TransferIncBackup(BackupTransferService_TransferIncBackupServer) error
}

func RegisterBackupTransferServiceServer(s *grpc.Server, srv BackupTransferServiceServer) {
	s.RegisterService(&_BackupTransferService_serviceDesc, srv)
}

func _BackupTransferService_TransferFullBackup_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BackupTransferServiceServer).TransferFullBackup(&backupTransferServiceTransferFullBackupServer{stream})
}

type BackupTransferService_TransferFullBackupServer interface {
	SendAndClose(*BackupReply) error
	Recv() (*FullBackupContentStream, error)
	grpc.ServerStream
}

type backupTransferServiceTransferFullBackupServer struct {
	grpc.ServerStream
}

func (x *backupTransferServiceTransferFullBackupServer) SendAndClose(m *BackupReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *backupTransferServiceTransferFullBackupServer) Recv() (*FullBackupContentStream, error) {
	m := new(FullBackupContentStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _BackupTransferService_TransferIncBackup_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BackupTransferServiceServer).TransferIncBackup(&backupTransferServiceTransferIncBackupServer{stream})
}

type BackupTransferService_TransferIncBackupServer interface {
	SendAndClose(*BackupReply) error
	Recv() (*IncBackupContentStream, error)
	grpc.ServerStream
}

type backupTransferServiceTransferIncBackupServer struct {
	grpc.ServerStream
}

func (x *backupTransferServiceTransferIncBackupServer) SendAndClose(m *BackupReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *backupTransferServiceTransferIncBackupServer) Recv() (*IncBackupContentStream, error) {
	m := new(IncBackupContentStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _BackupTransferService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tempbackuppb.BackupTransferService",
	HandlerType: (*BackupTransferServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransferFullBackup",
			Handler:       _BackupTransferService_TransferFullBackup_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "TransferIncBackup",
			Handler:       _BackupTransferService_TransferIncBackup_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "tempbackup/tempbackuppb/backup.proto",
}

func init() { proto.RegisterFile("tempbackup/tempbackuppb/backup.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x29, 0x49, 0xcd, 0x2d,
	0x48, 0x4a, 0x4c, 0xce, 0x2e, 0x2d, 0xd0, 0x47, 0x30, 0x0b, 0x92, 0xf4, 0x21, 0x0c, 0xbd, 0x82,
	0xa2, 0xfc, 0x92, 0x7c, 0x21, 0x1e, 0x64, 0x29, 0x25, 0x67, 0x2e, 0x71, 0xb7, 0xd2, 0x9c, 0x1c,
	0x27, 0x30, 0xdf, 0x39, 0x3f, 0xaf, 0x24, 0x35, 0xaf, 0x24, 0xb8, 0xa4, 0x28, 0x35, 0x31, 0x57,
	0x88, 0x8f, 0x8b, 0x29, 0x25, 0x49, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x88, 0x29, 0x25, 0x49,
	0x48, 0x82, 0x8b, 0x3d, 0x19, 0xa2, 0x40, 0x82, 0x49, 0x81, 0x51, 0x83, 0x27, 0x08, 0xc6, 0x55,
	0x0a, 0xe1, 0x12, 0xf3, 0xcc, 0x4b, 0x26, 0xc6, 0x0c, 0x01, 0x2e, 0xe6, 0x9c, 0xe2, 0x3c, 0xb0,
	0x7e, 0xce, 0x20, 0x10, 0x13, 0xd9, 0x54, 0x66, 0x54, 0x53, 0xd5, 0xb9, 0xb8, 0x21, 0x46, 0x06,
	0xa5, 0x16, 0xe4, 0x54, 0x82, 0x14, 0xe6, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x42, 0xcd, 0x83,
	0x71, 0x8d, 0xce, 0x32, 0x72, 0x89, 0x42, 0x54, 0x86, 0x14, 0x25, 0xe6, 0x15, 0xa7, 0xa5, 0x16,
	0x05, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0x45, 0x71, 0x09, 0xc1, 0x84, 0x10, 0xbe, 0x14,
	0x52, 0xd5, 0x43, 0x0e, 0x02, 0x3d, 0x1c, 0xfe, 0x97, 0x92, 0x44, 0x55, 0x86, 0xe4, 0x16, 0x25,
	0x06, 0x0d, 0x46, 0xa1, 0x08, 0x2e, 0x41, 0x98, 0xd9, 0x70, 0xcf, 0x0b, 0xa9, 0xa0, 0xea, 0xc1,
	0x1e, 0x2a, 0x04, 0x4c, 0x4e, 0x62, 0x03, 0x47, 0x94, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xdb,
	0xad, 0x23, 0xec, 0xd0, 0x01, 0x00, 0x00,
}
