// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tempbackup/tempbackuppb/backup.proto

/*
Package tempbackuppb is a generated protocol buffer package.

It is generated from these files:
	tempbackup/tempbackuppb/backup.proto

It has these top-level messages:
	FullBackupContentStream
	IncBackupContentStream
	BackupReply
	PostCheckpointsRequest
	PostCheckpointsResponse
*/
package tempbackuppb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FullBackupContentStream struct {
	Db      string `protobuf:"bytes,1,opt,name=db" json:"db,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *FullBackupContentStream) Reset()                    { *m = FullBackupContentStream{} }
func (m *FullBackupContentStream) String() string            { return proto.CompactTextString(m) }
func (*FullBackupContentStream) ProtoMessage()               {}
func (*FullBackupContentStream) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FullBackupContentStream) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *FullBackupContentStream) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type IncBackupContentStream struct {
	Db      string `protobuf:"bytes,1,opt,name=db" json:"db,omitempty"`
	Lsn     string `protobuf:"bytes,2,opt,name=lsn" json:"lsn,omitempty"`
	Content []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *IncBackupContentStream) Reset()                    { *m = IncBackupContentStream{} }
func (m *IncBackupContentStream) String() string            { return proto.CompactTextString(m) }
func (*IncBackupContentStream) ProtoMessage()               {}
func (*IncBackupContentStream) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IncBackupContentStream) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *IncBackupContentStream) GetLsn() string {
	if m != nil {
		return m.Lsn
	}
	return ""
}

func (m *IncBackupContentStream) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type BackupReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Key     string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *BackupReply) Reset()                    { *m = BackupReply{} }
func (m *BackupReply) String() string            { return proto.CompactTextString(m) }
func (*BackupReply) ProtoMessage()               {}
func (*BackupReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BackupReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BackupReply) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type PostCheckpointsRequest struct {
	Key     string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *PostCheckpointsRequest) Reset()                    { *m = PostCheckpointsRequest{} }
func (m *PostCheckpointsRequest) String() string            { return proto.CompactTextString(m) }
func (*PostCheckpointsRequest) ProtoMessage()               {}
func (*PostCheckpointsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PostCheckpointsRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PostCheckpointsRequest) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type PostCheckpointsResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *PostCheckpointsResponse) Reset()                    { *m = PostCheckpointsResponse{} }
func (m *PostCheckpointsResponse) String() string            { return proto.CompactTextString(m) }
func (*PostCheckpointsResponse) ProtoMessage()               {}
func (*PostCheckpointsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PostCheckpointsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*FullBackupContentStream)(nil), "tempbackuppb.FullBackupContentStream")
	proto.RegisterType((*IncBackupContentStream)(nil), "tempbackuppb.IncBackupContentStream")
	proto.RegisterType((*BackupReply)(nil), "tempbackuppb.BackupReply")
	proto.RegisterType((*PostCheckpointsRequest)(nil), "tempbackuppb.PostCheckpointsRequest")
	proto.RegisterType((*PostCheckpointsResponse)(nil), "tempbackuppb.PostCheckpointsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BackupTransferService service

type BackupTransferServiceClient interface {
	TransferFullBackup(ctx context.Context, opts ...grpc.CallOption) (BackupTransferService_TransferFullBackupClient, error)
	TransferIncBackup(ctx context.Context, opts ...grpc.CallOption) (BackupTransferService_TransferIncBackupClient, error)
	PostCheckpoints(ctx context.Context, in *PostCheckpointsRequest, opts ...grpc.CallOption) (*PostCheckpointsResponse, error)
}

type backupTransferServiceClient struct {
	cc *grpc.ClientConn
}

func NewBackupTransferServiceClient(cc *grpc.ClientConn) BackupTransferServiceClient {
	return &backupTransferServiceClient{cc}
}

func (c *backupTransferServiceClient) TransferFullBackup(ctx context.Context, opts ...grpc.CallOption) (BackupTransferService_TransferFullBackupClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BackupTransferService_serviceDesc.Streams[0], c.cc, "/tempbackuppb.BackupTransferService/TransferFullBackup", opts...)
	if err != nil {
		return nil, err
	}
	x := &backupTransferServiceTransferFullBackupClient{stream}
	return x, nil
}

type BackupTransferService_TransferFullBackupClient interface {
	Send(*FullBackupContentStream) error
	CloseAndRecv() (*BackupReply, error)
	grpc.ClientStream
}

type backupTransferServiceTransferFullBackupClient struct {
	grpc.ClientStream
}

func (x *backupTransferServiceTransferFullBackupClient) Send(m *FullBackupContentStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *backupTransferServiceTransferFullBackupClient) CloseAndRecv() (*BackupReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(BackupReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *backupTransferServiceClient) TransferIncBackup(ctx context.Context, opts ...grpc.CallOption) (BackupTransferService_TransferIncBackupClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BackupTransferService_serviceDesc.Streams[1], c.cc, "/tempbackuppb.BackupTransferService/TransferIncBackup", opts...)
	if err != nil {
		return nil, err
	}
	x := &backupTransferServiceTransferIncBackupClient{stream}
	return x, nil
}

type BackupTransferService_TransferIncBackupClient interface {
	Send(*IncBackupContentStream) error
	CloseAndRecv() (*BackupReply, error)
	grpc.ClientStream
}

type backupTransferServiceTransferIncBackupClient struct {
	grpc.ClientStream
}

func (x *backupTransferServiceTransferIncBackupClient) Send(m *IncBackupContentStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *backupTransferServiceTransferIncBackupClient) CloseAndRecv() (*BackupReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(BackupReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *backupTransferServiceClient) PostCheckpoints(ctx context.Context, in *PostCheckpointsRequest, opts ...grpc.CallOption) (*PostCheckpointsResponse, error) {
	out := new(PostCheckpointsResponse)
	err := grpc.Invoke(ctx, "/tempbackuppb.BackupTransferService/PostCheckpoints", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BackupTransferService service

type BackupTransferServiceServer interface {
	TransferFullBackup(BackupTransferService_TransferFullBackupServer) error
	TransferIncBackup(BackupTransferService_TransferIncBackupServer) error
	PostCheckpoints(context.Context, *PostCheckpointsRequest) (*PostCheckpointsResponse, error)
}

func RegisterBackupTransferServiceServer(s *grpc.Server, srv BackupTransferServiceServer) {
	s.RegisterService(&_BackupTransferService_serviceDesc, srv)
}

func _BackupTransferService_TransferFullBackup_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BackupTransferServiceServer).TransferFullBackup(&backupTransferServiceTransferFullBackupServer{stream})
}

type BackupTransferService_TransferFullBackupServer interface {
	SendAndClose(*BackupReply) error
	Recv() (*FullBackupContentStream, error)
	grpc.ServerStream
}

type backupTransferServiceTransferFullBackupServer struct {
	grpc.ServerStream
}

func (x *backupTransferServiceTransferFullBackupServer) SendAndClose(m *BackupReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *backupTransferServiceTransferFullBackupServer) Recv() (*FullBackupContentStream, error) {
	m := new(FullBackupContentStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _BackupTransferService_TransferIncBackup_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BackupTransferServiceServer).TransferIncBackup(&backupTransferServiceTransferIncBackupServer{stream})
}

type BackupTransferService_TransferIncBackupServer interface {
	SendAndClose(*BackupReply) error
	Recv() (*IncBackupContentStream, error)
	grpc.ServerStream
}

type backupTransferServiceTransferIncBackupServer struct {
	grpc.ServerStream
}

func (x *backupTransferServiceTransferIncBackupServer) SendAndClose(m *BackupReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *backupTransferServiceTransferIncBackupServer) Recv() (*IncBackupContentStream, error) {
	m := new(IncBackupContentStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _BackupTransferService_PostCheckpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCheckpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupTransferServiceServer).PostCheckpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tempbackuppb.BackupTransferService/PostCheckpoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupTransferServiceServer).PostCheckpoints(ctx, req.(*PostCheckpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BackupTransferService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tempbackuppb.BackupTransferService",
	HandlerType: (*BackupTransferServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostCheckpoints",
			Handler:    _BackupTransferService_PostCheckpoints_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransferFullBackup",
			Handler:       _BackupTransferService_TransferFullBackup_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "TransferIncBackup",
			Handler:       _BackupTransferService_TransferIncBackup_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "tempbackup/tempbackuppb/backup.proto",
}

func init() { proto.RegisterFile("tempbackup/tempbackuppb/backup.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0x69, 0x49, 0x34, 0x8c, 0xc4, 0x3f, 0x9b, 0x08, 0xc8, 0x89, 0x34, 0x90, 0xf4, 0x54,
	0x12, 0x39, 0x79, 0xb5, 0xc6, 0xc4, 0x9b, 0x29, 0x1c, 0x8c, 0x27, 0xdb, 0x32, 0x2a, 0x69, 0xbb,
	0xbb, 0xee, 0x6e, 0x4d, 0xfa, 0xa9, 0xfc, 0x8a, 0xa6, 0x5d, 0x17, 0x5a, 0x04, 0xf1, 0x36, 0xb3,
	0xfb, 0xe6, 0x97, 0xd9, 0xf7, 0x16, 0xc6, 0x0a, 0x33, 0x1e, 0x85, 0x71, 0x92, 0xf3, 0xe9, 0xa6,
	0xe4, 0xd1, 0x54, 0x17, 0x1e, 0x17, 0x4c, 0x31, 0xd2, 0xad, 0x5f, 0x39, 0x3e, 0xf4, 0xef, 0xf3,
	0x34, 0xbd, 0xad, 0x7a, 0x9f, 0x51, 0x85, 0x54, 0xcd, 0x95, 0xc0, 0x30, 0x23, 0xa7, 0x60, 0x2f,
	0xa3, 0x81, 0x35, 0xb2, 0xdc, 0x4e, 0x60, 0x2f, 0x23, 0x32, 0x80, 0xe3, 0x58, 0x0b, 0x06, 0xf6,
	0xc8, 0x72, 0xbb, 0x81, 0x69, 0x9d, 0x05, 0xf4, 0x1e, 0x68, 0xfc, 0x1f, 0xc6, 0x39, 0xb4, 0x53,
	0x49, 0xab, 0xf9, 0x4e, 0x50, 0x96, 0x75, 0x6a, 0xbb, 0x49, 0xbd, 0x81, 0x13, 0x8d, 0x0c, 0x90,
	0xa7, 0x45, 0x29, 0xcc, 0x50, 0xca, 0xf0, 0x0d, 0x7f, 0x78, 0xa6, 0x2d, 0xa1, 0x09, 0x16, 0x06,
	0x9a, 0x60, 0xe1, 0xdc, 0x41, 0xef, 0x91, 0x49, 0xe5, 0xbf, 0x63, 0x9c, 0x70, 0xb6, 0xa2, 0x4a,
	0x06, 0xf8, 0x91, 0xa3, 0x54, 0x46, 0x6b, 0xad, 0xb5, 0x7f, 0x3c, 0x6b, 0x06, 0xfd, 0x5f, 0x14,
	0xc9, 0x19, 0x95, 0xb8, 0x7f, 0x99, 0xeb, 0x2f, 0x1b, 0x2e, 0xf5, 0xda, 0x0b, 0x11, 0x52, 0xf9,
	0x8a, 0x62, 0x8e, 0xe2, 0x73, 0x15, 0x23, 0x79, 0x06, 0x62, 0x8e, 0x36, 0x96, 0x93, 0x89, 0x57,
	0xcf, 0xc3, 0xdb, 0x13, 0xc6, 0xf0, 0xaa, 0x29, 0xab, 0x19, 0xe3, 0xb4, 0x5c, 0x8b, 0x3c, 0xc1,
	0x85, 0x61, 0xaf, 0x93, 0x20, 0xe3, 0xe6, 0xcc, 0xee, 0x88, 0x0e, 0x91, 0x5f, 0xe0, 0x6c, 0xcb,
	0x84, 0x6d, 0xee, 0x6e, 0xa7, 0x87, 0x93, 0x03, 0x2a, 0xed, 0xa4, 0xd3, 0x8a, 0x8e, 0xaa, 0x7f,
	0x39, 0xfb, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x4e, 0xab, 0x47, 0x38, 0xbf, 0x02, 0x00, 0x00,
}
